#!/usr/bin/env python3
"""Extract monocypher b_comb_low/high/b_window tables from C into Go hand files.

Mechanical harvest (not sgoiter emit) — keeps tables bit-exact with upstream C.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path


def extract_array(c: str, name: str) -> list[list[list[int]]]:
    """Parse static const ge_precomp name[8] = { {{10},{10},{10}}, ... };"""
    m = re.search(rf"static const ge_precomp {name}\[8\]\s*=\s*\{{", c)
    if not m:
        raise SystemExit(f"missing {name}")
    i = m.end() - 1
    depth = 0
    start = i
    for j in range(i, len(c)):
        if c[j] == "{":
            depth += 1
        elif c[j] == "}":
            depth -= 1
            if depth == 0:
                body = c[start : j + 1]
                break
    else:
        raise SystemExit(f"unbalanced {name}")
    # numbers only, group as 8 * 3 * 10
    nums = [int(x) for x in re.findall(r"-?\d+", body)]
    # first number may be 8 from [8] already consumed — body starts at {
    if len(nums) < 240:
        raise SystemExit(f"{name}: want 240 limbs got {len(nums)}")
    nums = nums[:240]
    out = []
    k = 0
    for _ in range(8):
        entry = []
        for _ in range(3):
            entry.append(nums[k : k + 10])
            k += 10
        out.append(entry)
    return out


def emit_go(name: str, data: list[list[list[int]]], pkg: str) -> str:
    lines = [
        f"// Code generated by extract_comb_tables.py — monocypher {name}. DO NOT EDIT.",
        f"package {pkg}",
        "",
        f"var {name} = [8][3][10]int32{{",
    ]
    for e in data:
        lines.append("\t{")
        for fe in e:
            lines.append("\t\t{" + ",".join(str(x) for x in fe) + "},")
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    if len(sys.argv) < 3:
        print("usage: extract_comb_tables.py <monocypher.c> <out_dir> [package]", file=sys.stderr)
        sys.exit(2)
    cpath = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    pkg = sys.argv[3] if len(sys.argv) > 3 else "monocypher55"
    c = cpath.read_text()
    out_dir.mkdir(parents=True, exist_ok=True)
    for name in ("b_comb_low", "b_comb_high", "b_window"):
        data = extract_array(c, name)
        p = out_dir / f"{name}_table.go"
        p.write_text(emit_go(name, data, pkg))
        print("wrote", p)


if __name__ == "__main__":
    main()
