// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2painter

type C2_rect_t struct {
	X int
	Y int
	W int
	H int
}

type C2_painter_t struct {
	Pixels []uint32
	Width  int
	Height int
	Stride int
	Clip   C2_rect_t
}

type C2_node_t struct {
	Type_  uint16
	Flags  uint16
	X      int
	Y      int
	W      int
	H      int
	Color0 uint32
	Color1 uint32
	Param0 int
	Param1 int
}

type C2_scene_t struct {
	Nodes    *C2_node_t
	Count    int
	Capacity int
}

func C2_isqrt(val int) int {
	var v3 int
	var v5 int
	if val <= 0 {
		return 0
	}
	v3 = 0
	v5 = 0x40000000
	for v5 > val {
		v5 >>= 2
	}
	for v5 != 0 {
		if val >= (v3 + v5) {
			val -= (v3 + v5)
			v3 = (v3 >> 1) + v5
		} else {
			v3 >>= 1
		}
		v5 >>= 2
	}
	return v3
}

func C2_isqrt64(val int64) int64 {
	var v3 int64
	var v5 int64
	if val <= 0 {
		return 0
	}
	v3 = 0
	v5 = int64(uint64(1 << 62))
	for v5 > val {
		v5 = int64(v5 >> 2)
	}
	for v5 != 0 {
		if val >= (v3 + v5) {
			val -= (v3 + v5)
			v3 = int64(v3>>1) + v5
		} else {
			v3 = int64(v3 >> 1)
		}
		v5 = int64(v5 >> 2)
	}
	return v3
}

func C2_rgba(r byte, g byte, b byte, a byte) uint32 {
	return uint32(((uint32(r) | uint32(uint32(g)<<8)) | uint32(uint32(b)<<16)) | uint32(uint32(a)<<24))
}

func C2_rgba_premul(r byte, g byte, b byte, a byte) uint32 {
	return uint32((((((uint32(r) * uint32(a)) + 0x7f) / 0xff) | uint32((((uint32(g)*uint32(a))+0x7f)/0xff)<<8)) | uint32((((uint32(b)*uint32(a))+0x7f)/0xff)<<16)) | uint32(uint32(a)<<24))
}

func C2_blend_pixel(dst uint32, src uint32) uint32 {
	var v43 uint32
	var v50 uint32
	var v57 uint32
	var v64 uint32
	v6 := uint32(src>>24) & 0xff
	if v6 == 0xff {
		return src
	}
	if v6 == 0 {
		return dst
	}
	v11 := src & 0xff
	v16 := uint32(src>>8) & 0xff
	v21 := uint32(src>>16) & 0xff
	v24 := dst & 0xff
	v29 := uint32(dst>>8) & 0xff
	v34 := uint32(dst>>16) & 0xff
	v39 := uint32(dst>>24) & 0xff
	v42 := uint32(0xff) - v6
	v43 = v11 + (((v24 * v42) + 0x7f) / 0xff)
	v50 = v16 + (((v29 * v42) + 0x7f) / 0xff)
	v57 = v21 + (((v34 * v42) + 0x7f) / 0xff)
	v64 = v6 + (((v39 * v42) + 0x7f) / 0xff)
	if v43 > 0xff {
		v43 = 0xff
	}
	if v50 > 0xff {
		v50 = 0xff
	}
	if v57 > 0xff {
		v57 = 0xff
	}
	if v64 > 0xff {
		v64 = 0xff
	}
	return uint32(((v43 | uint32(v50<<8)) | uint32(v57<<16)) | uint32(v64<<24))
}

func C2_blend_pixel_cov(dst uint32, src uint32, cov uint32) uint32 {
	if cov == 0 {
		return dst
	}
	if cov >= 0xff {
		return uint32(C2_blend_pixel(dst, src))
	}
	v8 := src & 0xff
	v18 := uint32(src>>8) & 0xff
	v28 := uint32(src>>16) & 0xff
	v38 := uint32(src>>24) & 0xff
	return uint32(C2_blend_pixel(dst, ((((((v8 * cov) + 0x7f) / 0xff) | uint32((((v18*cov)+0x7f)/0xff)<<8)) | uint32((((v28*cov)+0x7f)/0xff)<<16)) | uint32((((v38*cov)+0x7f)/0xff)<<24))))
}

func C2_painter_init(p *C2_painter_t, pixels []uint32, width int, height int, stride int) {
	p.Pixels = pixels
	p.Width = width
	p.Height = height
	p.Stride = stride
	p.Clip.X = 0
	p.Clip.Y = 0
	p.Clip.W = width
	p.Clip.H = height
}

func C2_painter_set_clip(p *C2_painter_t, x int, y int, w int, h int) {
	_ = 0
	if x < 0 {
		w += x
		x = 0
	}
	if y < 0 {
		h += y
		y = 0
	}
	if (x + w) > p.Width {
		w = p.Width - x
	}
	if (y + h) > p.Height {
		h = p.Height - y
	}
	if w < 0 {
		w = 0
	}
	if h < 0 {
		h = 0
	}
	p.Clip.X = x
	p.Clip.Y = y
	p.Clip.W = w
	p.Clip.H = h
}

func C2_painter_reset_clip(p *C2_painter_t) {
	p.Clip.X = 0
	p.Clip.Y = 0
	p.Clip.W = p.Width
	p.Clip.H = p.Height
}

func C2_clear(p *C2_painter_t, color uint32) {
	var v16 int
	var v17 int
	var v22 int
	var v23 int
	_ = 0
	if (p.Width <= 0) || (p.Height <= 0) {
		return
	}
	if p.Stride == p.Width {
		v16 = p.Width * p.Height
		for v17 = 0; v17 < v16; v17++ {
			p.Pixels[v17] = color
		}
		return
	}
	for v22 = 0; v22 < p.Height; v22++ {
		v23 = 0
		for v23 < p.Width {
			p.Pixels[int((v22*p.Stride)+v23)] = color
			v23++
		}
	}
}

func C2_fill_rect(p *C2_painter_t, x int, y int, w int, h int, color uint32) {
	var v11 int
	var v12 int
	var v13 int
	var v15 int
	var v17 int
	var v20 int
	var v43 int
	var v44 int
	if (w <= 0) || (h <= 0) {
		return
	}
	v11 = x
	v12 = y
	v13 = x + w
	v15 = y + h
	v17 = p.Clip.X
	v20 = p.Clip.Y
	v28 := v17 + p.Clip.W
	v34 := v20 + p.Clip.H
	if v11 < v17 {
		v11 = v17
	}
	if v12 < v20 {
		v12 = v20
	}
	if v13 > v28 {
		v13 = v28
	}
	if v15 > v34 {
		v15 = v34
	}
	if (v11 >= v13) || (v12 >= v15) {
		return
	}
	v42 := uint32(color>>24) & 0xff
	if v42 == 0xff {
		for v43 = v12; v43 < v15; v43++ {
			v44 = v11
			for v44 < v13 {
				p.Pixels[int((v43*p.Stride)+v44)] = color
				v44++
			}
		}
	} else {
		if v42 > 0 {
			for v43 = v12; v43 < v15; v43++ {
				v44 = v11
				for v44 < v13 {
					p.Pixels[int((v43*p.Stride)+v44)] = C2_blend_pixel(p.Pixels[int((v43*p.Stride)+v44)], color)
					v44++
				}
			}
		}
	}
}

func C2_stroke_rect(p *C2_painter_t, x int, y int, w int, h int, stroke_width int, color uint32) {
	if ((stroke_width <= 0) || (w <= 0)) || (h <= 0) {
		return
	}
	v16 := stroke_width * 2
	if (v16 >= w) || (v16 >= h) {
		C2_fill_rect(p, x, y, w, h, color)
		return
	}
	C2_fill_rect(p, x, y, w, stroke_width, color)
	C2_fill_rect(p, x, ((y + h) - stroke_width), w, stroke_width, color)
	v27 := y + stroke_width
	v30 := h - (2 * stroke_width)
	C2_fill_rect(p, x, v27, stroke_width, v30, color)
	C2_fill_rect(p, ((x + w) - stroke_width), v27, stroke_width, v30, color)
}

func C2_fill_rounded_rect(p *C2_painter_t, x int, y int, w int, h int, radius int, color uint32) {
	var v43 int
	var v46 int
	var v119 int
	var v128 int
	var v130 int
	var v132 int
	var v134 int
	var v145 int64
	var v153 int
	var v154 int
	var v159 int
	var v166 int
	var v177 int
	var v180 int64
	var v195 int
	if (w <= 0) || (h <= 0) {
		return
	}
	if radius <= 0 {
		C2_fill_rect(p, x, y, w, h, color)
		return
	}
	if (radius * 2) > w {
		radius = w / 2
	}
	if (radius * 2) > h {
		radius = h / 2
	}
	v22 := x + radius
	v24 := 2 * radius
	C2_fill_rect(p, v22, y, (w - v24), h, color)
	v27 := y + radius
	v30 := h - v24
	C2_fill_rect(p, x, v27, radius, v30, color)
	v32 := x + w
	v33 := v32 - radius
	C2_fill_rect(p, v33, v27, radius, v30, color)
	v43 = p.Clip.X
	v46 = p.Clip.Y
	v54 := v43 + p.Clip.W
	v60 := v46 + p.Clip.H
	var v61 [4]int
	var v62 [4]int
	var v63 [4]int
	var v64 [4]int
	var v65 [4]int
	var v66 [4]int
	v61[0] = v22
	v62[0] = v27
	v63[0] = x
	v64[0] = y
	v65[0] = v22
	v66[0] = v27
	v61[1] = v33
	v62[1] = v27
	v63[1] = v33
	v64[1] = y
	v65[1] = v32
	v66[1] = v27
	v61[2] = v22
	v92 := y + h
	v93 := v92 - radius
	v62[2] = v93
	v63[2] = x
	v64[2] = v93
	v65[2] = v22
	v66[2] = v92
	v61[3] = v33
	v62[3] = v93
	v63[3] = v33
	v64[3] = v93
	v65[3] = v32
	v66[3] = v92
	for v119 = 0; v119 < 4; v119++ {
		v128 = v63[v119]
		v130 = v64[v119]
		v132 = v65[v119]
		v134 = v66[v119]
		if v128 < v43 {
			v128 = v43
		}
		if v130 < v46 {
			v130 = v46
		}
		if v132 > v54 {
			v132 = v54
		}
		if v134 > v60 {
			v134 = v60
		}
		v145 = func() int64 {
			if (int64(radius) - 1) > 0 {
				return ((int64(radius) - 1) * (int64(radius) - 1))
			}
			return 0
		}()
		v153 = v130
		for v153 < v134 {
			v159 = v153 * p.Stride
			v166 = func() int {
				if v153 < v62[v119] {
					return (v62[v119] - v153)
				}
				return ((v153 - v62[v119]) + 1)
			}()
			v154 = v128
			for v154 < v132 {
				v177 = func() int {
					if v154 < v61[v119] {
						return (v61[v119] - v154)
					}
					return ((v154 - v61[v119]) + 1)
				}()
				v180 = (int64(v177) * int64(v177)) + (int64(v166) * int64(v166))
				if v180 <= v145 {
					p.Pixels[v159+v154] = C2_blend_pixel(p.Pixels[v159+v154], color)
				} else {
					if v180 < (int64(radius+2) * (int64(radius) + 2)) {
						v195 = ((radius << 8) + 128) - int(C2_isqrt64(int64(v180<<16)))
						if v195 >= 255 {
							p.Pixels[v159+v154] = C2_blend_pixel(p.Pixels[v159+v154], color)
						} else {
							if v195 > 0 {
								p.Pixels[v159+v154] = C2_blend_pixel_cov(p.Pixels[v159+v154], color, uint32(v195))
							}
						}
					}
				}
				v154++
			}
			v153++
		}
	}
}

func C2_stroke_rounded_rect(p *C2_painter_t, x int, y int, w int, h int, radius int, stroke_width int, color uint32) {
	var v59 int
	var v69 int
	var v72 int
	var v145 int
	var v154 int
	var v156 int
	var v158 int
	var v160 int
	var v162 int
	var v163 int
	var v168 int
	var v175 int
	var v186 int
	var v194 int
	var v202 int
	var v203 int
	if ((stroke_width <= 0) || (w <= 0)) || (h <= 0) {
		return
	}
	v17 := stroke_width * 2
	if (v17 >= w) || (v17 >= h) {
		C2_fill_rounded_rect(p, x, y, w, h, radius, color)
		return
	}
	if radius <= 0 {
		C2_stroke_rect(p, x, y, w, h, stroke_width, color)
		return
	}
	if (radius * 2) > w {
		radius = w / 2
	}
	if (radius * 2) > h {
		radius = h / 2
	}
	v34 := x + radius
	v36 := 2 * radius
	v37 := w - v36
	C2_fill_rect(p, v34, y, v37, stroke_width, color)
	C2_fill_rect(p, v34, ((y + h) - stroke_width), v37, stroke_width, color)
	v46 := y + radius
	v49 := h - v36
	C2_fill_rect(p, x, v46, stroke_width, v49, color)
	C2_fill_rect(p, ((x + w) - stroke_width), v46, stroke_width, v49, color)
	v59 = radius - stroke_width
	if v59 < 0 {
		v59 = 0
	}
	v69 = p.Clip.X
	v72 = p.Clip.Y
	v80 := v69 + p.Clip.W
	v86 := v72 + p.Clip.H
	var v87 [4]int
	var v88 [4]int
	var v89 [4]int
	var v90 [4]int
	var v91 [4]int
	var v92 [4]int
	v93 := x + radius
	v87[0] = v93
	v95 := y + radius
	v88[0] = v95
	v89[0] = x
	v90[0] = y
	v91[0] = v93
	v92[0] = v95
	v103 := x + w
	v104 := v103 - radius
	v87[1] = v104
	v88[1] = v95
	v89[1] = v104
	v90[1] = y
	v91[1] = v103
	v92[1] = v95
	v87[2] = v93
	v118 := y + h
	v119 := v118 - radius
	v88[2] = v119
	v89[2] = x
	v90[2] = v119
	v91[2] = v93
	v92[2] = v118
	v87[3] = v104
	v88[3] = v119
	v89[3] = v104
	v90[3] = v119
	v91[3] = v103
	v92[3] = v118
	for v145 = 0; v145 < 4; v145++ {
		v154 = v89[v145]
		v156 = v90[v145]
		v158 = v91[v145]
		v160 = v92[v145]
		if v154 < v69 {
			v154 = v69
		}
		if v156 < v72 {
			v156 = v72
		}
		if v158 > v80 {
			v158 = v80
		}
		if v160 > v86 {
			v160 = v86
		}
		v162 = v156
		for v162 < v160 {
			v168 = v162 * p.Stride
			v175 = func() int {
				if v162 < v88[v145] {
					return (v88[v145] - v162)
				}
				return ((v162 - v88[v145]) + 1)
			}()
			v163 = v154
			for v163 < v158 {
				v186 = func() int {
					if v163 < v87[v145] {
						return (v87[v145] - v163)
					}
					return ((v163 - v87[v145]) + 1)
				}()
				v194 = int(C2_isqrt64(int64(((int64(v186) * int64(v186)) + (int64(v175) * int64(v175))) << 16)))
				v202 = (v194 + 128) - (v59 << 8)
				v203 = ((radius << 8) + 128) - v194
				if v202 < v203 {
					v203 = v202
				}
				if v203 >= 255 {
					p.Pixels[v168+v163] = C2_blend_pixel(p.Pixels[v168+v163], color)
				} else {
					if v203 > 0 {
						p.Pixels[v168+v163] = C2_blend_pixel_cov(p.Pixels[v168+v163], color, uint32(v203))
					}
				}
				v163++
			}
			v162++
		}
	}
}

func C2_fill_circle(p *C2_painter_t, cx int, cy int, radius int, color uint32) {
	var v9 int
	var v13 int
	var v17 int
	var v21 int
	var v25 int
	var v28 int
	var v70 int
	var v71 int
	var v76 int
	var v93 int64
	var v106 int
	if radius <= 0 {
		return
	}
	v9 = (cx - radius) - 1
	v13 = (cx + radius) + 1
	v17 = (cy - radius) - 1
	v21 = (cy + radius) + 1
	v25 = p.Clip.X
	v28 = p.Clip.Y
	v36 := v25 + p.Clip.W
	v42 := v28 + p.Clip.H
	if v9 < v25 {
		v9 = v25
	}
	if v17 < v28 {
		v17 = v28
	}
	if v13 > v36 {
		v13 = v36
	}
	if v21 > v42 {
		v21 = v42
	}
	if (v9 >= v13) || (v17 >= v21) {
		return
	}
	v47 := int64(radius)
	v59 := func() int64 {
		if (v47 - 1) > 0 {
			return ((((v47 - 1) * 0x100) * (v47 - 1)) * 0x100)
		}
		return int64(0)
	}()
	for v70 = v17; v70 < v21; v70++ {
		v76 = v70 * p.Stride
		v71 = v9
		for v71 < v13 {
			v93 = ((int64(v71-cx) * 0x100) * (int64(v71-cx) * 0x100)) + ((int64(v70-cy) * 0x100) * (int64(v70-cy) * 0x100))
			if v93 <= v59 {
				p.Pixels[v76+v71] = C2_blend_pixel(p.Pixels[v76+v71], color)
			} else {
				if v93 < ((((v47 + 2) * 0x100) * (v47 + 2)) * 0x100) {
					v106 = ((radius << 8) + 128) - int(C2_isqrt64(v93))
					if v106 >= 255 {
						p.Pixels[v76+v71] = C2_blend_pixel(p.Pixels[v76+v71], color)
					} else {
						if v106 > 0 {
							p.Pixels[v76+v71] = C2_blend_pixel_cov(p.Pixels[v76+v71], color, uint32(v106))
						}
					}
				}
			}
			v71++
		}
	}
}

func C2_stroke_circle(p *C2_painter_t, cx int, cy int, radius int, stroke_width int, color uint32) {
	var v16 int
	var v21 int
	var v26 int
	var v31 int
	var v36 int
	var v39 int
	var v61 int
	var v68 int
	var v69 int
	var v74 int
	var v94 int
	var v102 int
	var v103 int
	if (radius <= 0) || (stroke_width <= 0) {
		return
	}
	v15 := (stroke_width + 1) / 2
	v16 = ((cx - radius) - v15) - 1
	v21 = ((cx + radius) + v15) + 1
	v26 = ((cy - radius) - v15) - 1
	v31 = ((cy + radius) + v15) + 1
	v36 = p.Clip.X
	v39 = p.Clip.Y
	v47 := v36 + p.Clip.W
	v53 := v39 + p.Clip.H
	if v16 < v36 {
		v16 = v36
	}
	if v26 < v39 {
		v26 = v39
	}
	if v21 > v47 {
		v21 = v47
	}
	if v31 > v53 {
		v31 = v53
	}
	if (v16 >= v21) || (v26 >= v31) {
		return
	}
	v61 = radius - v15
	if v61 < 0 {
		v61 = 0
	}
	for v68 = v26; v68 < v31; v68++ {
		v74 = v68 * p.Stride
		v69 = v16
		for v69 < v21 {
			v94 = int(C2_isqrt64(((int64(v69-cx) * 0x100) * (int64(v69-cx) * 0x100)) + ((int64(v68-cy) * 0x100) * (int64(v68-cy) * 0x100))))
			v102 = (v94 + 128) - (v61 << 8)
			v103 = (((radius + v15) << 8) + 128) - v94
			if v102 < v103 {
				v103 = v102
			}
			if v103 >= 255 {
				p.Pixels[v74+v69] = C2_blend_pixel(p.Pixels[v74+v69], color)
			} else {
				if v103 > 0 {
					p.Pixels[v74+v69] = C2_blend_pixel_cov(p.Pixels[v74+v69], color, uint32(v103))
				}
			}
			v69++
		}
	}
}

func C2_fill_ellipse(p *C2_painter_t, cx int, cy int, rx int, ry int, color uint32) {
	var v11 int
	var v15 int
	var v19 int
	var v23 int
	var v27 int
	var v30 int
	var v57 int64
	var v60 int
	var v61 int
	var v66 int
	var v84 int
	if (rx <= 0) || (ry <= 0) {
		return
	}
	v11 = (cx - rx) - 1
	v15 = (cx + rx) + 1
	v19 = (cy - ry) - 1
	v23 = (cy + ry) + 1
	v27 = p.Clip.X
	v30 = p.Clip.Y
	v38 := v27 + p.Clip.W
	v44 := v30 + p.Clip.H
	if v11 < v27 {
		v11 = v27
	}
	if v19 < v30 {
		v19 = v30
	}
	if v15 > v38 {
		v15 = v38
	}
	if v23 > v44 {
		v23 = v44
	}
	if (v11 >= v15) || (v19 >= v23) {
		return
	}
	v59 := max(rx, ry)
	v57 = int64(v59)
	for v60 = v19; v60 < v23; v60++ {
		v66 = v60 * p.Stride
		v61 = v11
		for v61 < v15 {
			v84 = 0
			if v57 > 0 {
				v84 = int(((((int64(rx) * int64(ry)) - C2_isqrt64(((int64(v61-cx)*int64(v61-cx))*(int64(ry)*int64(ry)))+((int64(v60-cy)*int64(v60-cy))*(int64(rx)*int64(rx))))) * 255) / v57) + 128)
			}
			if v84 >= 255 {
				p.Pixels[v66+v61] = C2_blend_pixel(p.Pixels[v66+v61], color)
			} else {
				if v84 > 0 {
					p.Pixels[v66+v61] = C2_blend_pixel_cov(p.Pixels[v66+v61], color, uint32(v84))
				}
			}
			v61++
		}
	}
}

func C2_stroke_ellipse(p *C2_painter_t, cx int, cy int, rx int, ry int, stroke_width int, color uint32) {
	var v20 int
	var v25 int
	var v30 int
	var v35 int
	var v40 int
	var v43 int
	var v61 int64
	var v63 int64
	var v65 int64
	var v69 int64
	var v88 int
	var v89 int
	var v94 int
	var v98 int64
	var v108 int64
	var v122 int64
	var v123 int64
	var v124 int
	if ((rx <= 0) || (ry <= 0)) || (stroke_width <= 0) {
		return
	}
	v19 := (stroke_width + 1) / 2
	v20 = ((cx - rx) - v19) - 1
	v25 = ((cx + rx) + v19) + 1
	v30 = ((cy - ry) - v19) - 1
	v35 = ((cy + ry) + v19) + 1
	v40 = p.Clip.X
	v43 = p.Clip.Y
	v51 := v40 + p.Clip.W
	v57 := v43 + p.Clip.H
	if v20 < v40 {
		v20 = v40
	}
	if v30 < v43 {
		v30 = v43
	}
	if v25 > v51 {
		v25 = v51
	}
	if v35 > v57 {
		v35 = v57
	}
	if (v20 >= v25) || (v30 >= v35) {
		return
	}
	v61 = int64(rx + v19)
	v63 = int64(ry + v19)
	v65 = int64(rx - v19)
	if v65 < 0 {
		v65 = 0
	}
	v69 = int64(ry - v19)
	if v69 < 0 {
		v69 = 0
	}
	v87 := max(v61, v63)
	for v88 = v30; v88 < v35; v88++ {
		v94 = v88 * p.Stride
		v98 = int64(v88-cy) * int64(v88-cy)
		v89 = v20
		for v89 < v25 {
			v108 = int64(v89-cx) * int64(v89-cx)
			v122 = C2_isqrt64((v108*(v69*v69))+(v98*(v65*v65))) - (v65 * v69)
			v123 = (v61 * v63) - C2_isqrt64((v108*(v63*v63))+(v98*(v61*v61)))
			if v122 < v123 {
				v123 = v122
			}
			v124 = 0
			if v87 > 0 {
				v124 = int(((v123 * 255) / v87) + 128)
			}
			if v124 >= 255 {
				p.Pixels[v94+v89] = C2_blend_pixel(p.Pixels[v94+v89], color)
			} else {
				if v124 > 0 {
					p.Pixels[v94+v89] = C2_blend_pixel_cov(p.Pixels[v94+v89], color, uint32(v124))
				}
			}
			v89++
		}
	}
}

func C2_draw_line(p *C2_painter_t, x0 int, y0 int, x1 int, y1 int, stroke_width int, color uint32) {
	var v8 int64
	var v10 int64
	var v29 int
	var v32 int
	var v35 int
	var v38 int
	var v45 int
	var v48 int
	var v77 int
	var v78 int
	var v80 int
	var v81 int
	var v82 int
	var v87 int64
	var v88 int64
	var v89 int64
	var v91 int64
	var v103 int64
	var v119 int
	var v129 int64
	var v130 int64
	var v174 int
	if stroke_width <= 0 {
		return
	}
	v8 = int64(x1 - x0)
	v10 = int64(y1 - y0)
	v15 := (v8 * v8) + (v10 * v10)
	if v15 == 0 {
		C2_fill_circle(p, x0, y0, ((stroke_width + 1) / 2), color)
		return
	}
	v28 := ((stroke_width + 3) / 2) + 1
	v29 = min(x0, x1)
	v32 = max(x0, x1)
	v35 = min(y0, y1)
	v38 = max(y0, y1)
	v29 -= v28
	v32 += v28
	v35 -= v28
	v38 += v28
	v45 = p.Clip.X
	v48 = p.Clip.Y
	v56 := v45 + p.Clip.W
	v62 := v48 + p.Clip.H
	if v29 < v45 {
		v29 = v45
	}
	if v35 < v48 {
		v35 = v48
	}
	if v32 > v56 {
		v32 = v56
	}
	if v38 > v62 {
		v38 = v62
	}
	if (v29 >= v32) || (v35 >= v38) {
		return
	}
	v72 := int64(v28) * (C2_isqrt64(v15) + 1)
	v77 = v35
	for v77 < v38 {
		v81 = v29
		v82 = v32
		if v10 != 0 {
			v87 = v8 * int64(v77-y0)
			if v10 > 0 {
				v91 = int64(x0)
				v88 = (v91 + ((v87 - v72) / v10)) - 1
				v89 = (v91 + ((v87 + v72) / v10)) + 2
			} else {
				v103 = int64(x0)
				v88 = (v103 + ((v87 + v72) / v10)) - 1
				v89 = (v103 + ((v87 - v72) / v10)) + 2
			}
			if int(v88) > v81 {
				v81 = int(v88)
			}
			if int(v89) < v82 {
				v82 = int(v89)
			}
		}
		if v81 < v29 {
			v81 = v29
		}
		if v82 > v32 {
			v82 = v32
		}
		if v81 >= v82 {
			v80 = v77 + 1
			v77 = v80
			continue
		}
		v119 = v77 * p.Stride
		for v78 = v81; v78 < v82; v78++ {
			v129 = (int64(v78-x0) * v8) + (int64(v77-y0) * v10)
			v130 = 0
			if v129 >= v15 {
				v130 = 0x100
			} else {
				if v129 > 0 {
					v130 = (v129 * 0x100) / v15
				}
			}
			v174 = int(((int64(stroke_width) * 128) + 128) - int64(int(C2_isqrt64(((((int64(v78)*0x100)+128)-((int64(x0)*0x100)+(v8*v130)))*(((int64(v78)*0x100)+128)-((int64(x0)*0x100)+(v8*v130))))+((((int64(v77)*0x100)+128)-((int64(y0)*0x100)+(v10*v130)))*(((int64(v77)*0x100)+128)-((int64(y0)*0x100)+(v10*v130))))))))
			if v174 >= 255 {
				p.Pixels[v119+v78] = C2_blend_pixel(p.Pixels[v119+v78], color)
			} else {
				if v174 > 0 {
					p.Pixels[v119+v78] = C2_blend_pixel_cov(p.Pixels[v119+v78], color, uint32(v174))
				}
			}
		}
		v80 = v77 + 1
		v77 = v80
	}
}

func C2_blit_mask(p *C2_painter_t, dst_x int, dst_y int, w int, h int, mask []byte, mask_stride int, color uint32) {
	var v13 int
	var v14 int
	var v15 int
	var v17 int
	var v19 int
	var v22 int
	var v40 int
	var v41 int
	var v55 byte
	if (w <= 0) || (h <= 0) {
		return
	}
	v13 = dst_x
	v14 = dst_y
	v15 = dst_x + w
	v17 = dst_y + h
	v19 = p.Clip.X
	v22 = p.Clip.Y
	v30 := v19 + p.Clip.W
	v36 := v22 + p.Clip.H
	if v13 < v19 {
		v13 = v19
	}
	if v14 < v22 {
		v14 = v22
	}
	if v15 > v30 {
		v15 = v30
	}
	if v17 > v36 {
		v17 = v36
	}
	if (v13 >= v15) || (v14 >= v17) {
		return
	}
	for v40 = v14; v40 < v17; v40++ {
		v41 = v13
		for v41 < v15 {
			v55 = mask[int(((v40-dst_y)*mask_stride)+(v41-dst_x))]
			if v55 > 0 {
				p.Pixels[int((v40*p.Stride)+v41)] = C2_blend_pixel_cov(p.Pixels[int((v40*p.Stride)+v41)], color, uint32(v55))
			}
			v41++
		}
	}
}

func C2_blit_rgba(p *C2_painter_t, dst_x int, dst_y int, w int, h int, src []uint32, src_stride int) {
	var v12 int
	var v13 int
	var v14 int
	var v16 int
	var v18 int
	var v21 int
	var v39 int
	var v40 int
	if (w <= 0) || (h <= 0) {
		return
	}
	v12 = dst_x
	v13 = dst_y
	v14 = dst_x + w
	v16 = dst_y + h
	v18 = p.Clip.X
	v21 = p.Clip.Y
	v29 := v18 + p.Clip.W
	v35 := v21 + p.Clip.H
	if v12 < v18 {
		v12 = v18
	}
	if v13 < v21 {
		v13 = v21
	}
	if v14 > v29 {
		v14 = v29
	}
	if v16 > v35 {
		v16 = v35
	}
	if (v12 >= v14) || (v13 >= v16) {
		return
	}
	for v39 = v13; v39 < v16; v39++ {
		v40 = v12
		for v40 < v14 {
			p.Pixels[int((v39*p.Stride)+v40)] = C2_blend_pixel(p.Pixels[int((v39*p.Stride)+v40)], src[int(((v39-dst_y)*src_stride)+(v40-dst_x))])
			v40++
		}
	}
}

func C2_fill_linear_gradient(p *C2_painter_t, x int, y int, w int, h int, color0 uint32, color1 uint32, vertical int) {
	var v13 int
	var v14 int
	var v15 int
	var v17 int
	var v19 int
	var v22 int
	var v80 int
	var v81 int
	if (w <= 0) || (h <= 0) {
		return
	}
	v13 = x
	v14 = y
	v15 = x + w
	v17 = y + h
	v19 = p.Clip.X
	v22 = p.Clip.Y
	v30 := v19 + p.Clip.W
	v36 := v22 + p.Clip.H
	if v13 < v19 {
		v13 = v19
	}
	if v14 < v22 {
		v14 = v22
	}
	if v15 > v30 {
		v15 = v30
	}
	if v17 > v36 {
		v17 = v36
	}
	if (v13 >= v15) || (v14 >= v17) {
		return
	}
	v42 := color0 & 0xff
	v47 := uint32(color0>>8) & 0xff
	v52 := uint32(color0>>16) & 0xff
	v57 := uint32(color0>>24) & 0xff
	v60 := color1 & 0xff
	v65 := uint32(color1>>8) & 0xff
	v70 := uint32(color1>>16) & 0xff
	v75 := uint32(color1>>24) & 0xff
	v77 := func() int {
		if vertical != 0 {
			return h
		}
		return w
	}()
	if v77 <= 1 {
		C2_fill_rect(p, x, y, w, h, color0)
		return
	}
	if vertical != 0 {
		for v80 = v14; v80 < v17; v80++ {
			v81 = v13
			for v81 < v15 {
				p.Pixels[int((v80*p.Stride)+v81)] = C2_blend_pixel(p.Pixels[int((v80*p.Stride)+v81)], (((uint32((((int(v42)*(255-(((v80-y)*255)/(v77-1))))+(int(v60)*(((v80-y)*255)/(v77-1))))+127)/255) | (uint32((((int(v47)*(255-(((v80-y)*255)/(v77-1))))+(int(v65)*(((v80-y)*255)/(v77-1))))+127)/255) << 8)) | (uint32((((int(v52)*(255-(((v80-y)*255)/(v77-1))))+(int(v70)*(((v80-y)*255)/(v77-1))))+127)/255) << 16)) | (uint32((((int(v57)*(255-(((v80-y)*255)/(v77-1))))+(int(v75)*(((v80-y)*255)/(v77-1))))+127)/255) << 24)))
				v81++
			}
		}
	} else {
		for v81 = v13; v81 < v15; v81++ {
			v80 = v14
			for v80 < v17 {
				p.Pixels[int((v80*p.Stride)+v81)] = C2_blend_pixel(p.Pixels[int((v80*p.Stride)+v81)], (((uint32((((int(v42)*(255-(((v81-x)*255)/(v77-1))))+(int(v60)*(((v81-x)*255)/(v77-1))))+127)/255) | (uint32((((int(v47)*(255-(((v81-x)*255)/(v77-1))))+(int(v65)*(((v81-x)*255)/(v77-1))))+127)/255) << 8)) | (uint32((((int(v52)*(255-(((v81-x)*255)/(v77-1))))+(int(v70)*(((v81-x)*255)/(v77-1))))+127)/255) << 16)) | (uint32((((int(v57)*(255-(((v81-x)*255)/(v77-1))))+(int(v75)*(((v81-x)*255)/(v77-1))))+127)/255) << 24)))
				v80++
			}
		}
	}
}

func C2_draw_cursor(p *C2_painter_t, x int, y int, w int, h int, style int, color uint32) {
	var v16 int
	var v22 int
	if (w <= 0) || (h <= 0) {
		return
	}
	switch style {
	case 0:
		C2_fill_rect(p, x, y, w, h, color)
	case 1:
		v16 = func() int {
			if 2 > uint32(w) {
				return w
			}
			return 2
		}()
		C2_fill_rect(p, x, y, v16, h, color)
	case 2:
		v22 = func() int {
			if 2 > uint32(h) {
				return h
			}
			return 2
		}()
		C2_fill_rect(p, x, ((y + h) - v22), w, v22, color)
	case 3:
		C2_stroke_rect(p, x, y, w, h, 1, color)
	default:
		C2_fill_rect(p, x, y, w, h, color)
	}
}

func C2_scene_render(p *C2_painter_t, nodes []C2_node_t, count int) {
	var v11 int
	var v15 *C2_node_t
	_ = 0
	if ((p == nil) || (nodes == nil)) || (count <= 0) {
		return
	}
	for v11 = 0; v11 < count; v11++ {
		v15 = &nodes[v11]
		switch v15.Type_ {
		case 1:
			if v15.Flags == 1 {
				C2_stroke_rect(p, v15.X, v15.Y, v15.W, v15.H, v15.Param0, v15.Color0)
			} else {
				C2_fill_rect(p, v15.X, v15.Y, v15.W, v15.H, v15.Color0)
			}
		case 2:
			if v15.Flags == 1 {
				C2_stroke_rounded_rect(p, v15.X, v15.Y, v15.W, v15.H, v15.Param0, v15.Param1, v15.Color0)
			} else {
				C2_fill_rounded_rect(p, v15.X, v15.Y, v15.W, v15.H, v15.Param0, v15.Color0)
			}
		case 3:
			if v15.Flags == 1 {
				C2_stroke_circle(p, v15.X, v15.Y, v15.Param0, v15.Param1, v15.Color0)
			} else {
				C2_fill_circle(p, v15.X, v15.Y, v15.Param0, v15.Color0)
			}
		case 4:
			C2_fill_ellipse(p, v15.X, v15.Y, v15.Param0, v15.Param1, v15.Color0)
		case 5:
			C2_draw_line(p, v15.X, v15.Y, v15.W, v15.H, v15.Param0, v15.Color0)
		default:
		}
	}
}
