// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package adv_tls_depth

func Leaf(x uint32) uint32 {
	return uint32((x * 0x9e3779b1) ^ (x >> 16))
}

func M1(x uint32) uint32 {
	return uint32(Leaf(x + 1))
}

func M2(x uint32) uint32 {
	return uint32(M1(x ^ 0x85ebca6b))
}

func M3(x uint32) uint32 {
	return uint32(M2(x + 0xc2b2ae35))
}

func M4(x uint32) uint32 {
	return uint32(M3(x ^ (x << 13)))
}

func Adv_tls_depth(x uint32) uint32 {
	return uint32(M4(x))
}

