// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package adv_computed_goto

func Adv_dispatch(op uint32, a uint32, b uint32) uint32 {
	switch (op & 7) {
		case 0:
			return uint32(a + b)
		fallthrough
		case 1:
			return uint32(a - b)
		fallthrough
		case 2:
			return uint32(a ^ b)
		fallthrough
		case 3:
			return uint32(a | b)
		fallthrough
		case 4:
			return uint32(a & b)
		fallthrough
		case 5:
			return uint32((a << uint8(b & 31)) | (a >> uint8(uint32(32) - (b & 31))))
		fallthrough
		case 6:
			return uint32(a * (b | 1))
		fallthrough
		default:
			return uint32(a ^ (b * 0x9e3779b1))
	}
}

