// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package adv_stack_buf

func Adv_stack_workspace(in []byte, n uint64) uint32 {
	var v3 uint32
	var v4 uint32
	var v2 [4096]uint8
	v4 = 0x811c9dc5
	if n > 64 {
		n = 64
	}
	v3 = 0
	for uint64(v3) < n {
		v2[int(v3)] = in[int(v3)] ^ uint8(v3)
		v3 = v3 + 1
	}
	v3 = 0
	for uint64(v3) < n {
		v4 = v4 ^ uint32(v2[int(v3)])
		v4 = v4 * 0x1000193
		v3 = v3 + 1
	}
	v4 = v4 ^ uint32(v2[64])
	return v4
}

