// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package base64_simd

const b64_table = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"

func Base64_encode_stream(src []byte, len_ uint64, dst []byte) uint64 {
	var table = [64]byte{
		'A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P',
		'Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f',
		'g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v',
		'w','x','y','z','0','1','2','3','4','5','6','7','8','9','+','/',
	}
	n := int(len_)
	if n > len(src) { n = len(src) }
	src = src[:n]
	if n > 0 { _ = src[n-1] }
	i, j := 0, 0
	for ; i+2 < n; i += 3 {
		v := uint32(src[i])<<16 | uint32(src[i+1])<<8 | uint32(src[i+2])
		dst[j] = table[(v>>18)&63]; j++
		dst[j] = table[(v>>12)&63]; j++
		dst[j] = table[(v>>6)&63]; j++
		dst[j] = table[v&63]; j++
	}
	if i < n {
		v := uint32(src[i]) << 16
		if i+1 < n { v |= uint32(src[i+1]) << 8 }
		dst[j] = table[(v>>18)&63]; j++
		dst[j] = table[(v>>12)&63]; j++
		if i+1 < n { dst[j] = table[(v>>6)&63]; j++ } else { dst[j] = '='; j++ }
		dst[j] = '='; j++
	}
	return uint64(j)
}

