// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package chacha20_qr

import "math/bits"

func Chacha20_quarter_round(a *uint32, b *uint32, c *uint32, d *uint32) {
	v4 := *b
	*a = *a + v4
	v7 := *a
	*d = *d ^ v7
	v10 := *d
	*d = bits.RotateLeft32(v10, 16)
	v19 := *d
	*c = *c + v19
	v22 := *c
	*b = v4 ^ v22
	v25 := *b
	*b = bits.RotateLeft32(v25, 12)
	v34 := *b
	*a = v7 + v34
	*d = v19 ^ *a
	v40 := *d
	*d = bits.RotateLeft32(v40, 8)
	*c = v22 + *d
	*b = v34 ^ *c
	v55 := *b
	*b = bits.RotateLeft32(v55, 7)
}

