// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package cjson_number_dogfood

func Cjson_parse_u64_dogfood(s []byte, len_ uint64, nconsumed *uint64) uint64 {
	var v3 uint64
	var v5 uint64
	v3 = 0
	v5 = v3
	if nconsumed != nil {
		*nconsumed = uint64(0)
	}
	if (s == nil) || (len_ == 0) {
		return 0
	}
	for v3 < len_ {
		v15 := s[int(v3)]
		v17 := uint8('0')
		if !(v15 >= v17) { break }
		if !(v15 <= '9') { break }
		v5 = (v5 * 10) + uint64(v15 - v17)
		v3 = v3 + 1
	}
	if nconsumed != nil {
		*nconsumed = v3
	}
	return v5
}

func Cjson_is_null_lit_dogfood(s []byte, len_ uint64) uint64 {
	if (s == nil) || (len_ < 4) {
		return 0
	}
	if (((s[0] == 'n') && (s[1] == 'u')) && (s[2] == 'l')) && (s[3] == 'l') {
		return 1
	}
	return 0
}

