// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package crc32_ieee

func Crc32_ieee(data []byte, len_ uint64) uint32 {
	var v2 uint32
	var v4 uint32
	var v15 uint32
	var v17 uint32
	var v18 int
	var v20 int
	var v21 uint32
	var v23 uint32
	var v25 uint32
	var v26 uint32
	v2 = 0xffffffff
	v4 = 0
	for uint64(v4) < len_ {
		v2 = v2 ^ uint32(data[int(v4)])
		v17 = v2 & 1
		v18 = int(v17)
		v20 = -v18
		v21 = uint32(v20)
		v15 = v21
		v23 = v2 >> 1
		v25 = 0xedb88320 & v15
		v26 = v23 ^ v25
		v2 = v26
		v17 = v2 & 1
		v18 = int(v17)
		v20 = -v18
		v21 = uint32(v20)
		v15 = v21
		v23 = v2 >> 1
		v25 = 0xedb88320 & v15
		v26 = v23 ^ v25
		v2 = v26
		v17 = v2 & 1
		v18 = int(v17)
		v20 = -v18
		v21 = uint32(v20)
		v15 = v21
		v23 = v2 >> 1
		v25 = 0xedb88320 & v15
		v26 = v23 ^ v25
		v2 = v26
		v17 = v2 & 1
		v18 = int(v17)
		v20 = -v18
		v21 = uint32(v20)
		v15 = v21
		v23 = v2 >> 1
		v25 = 0xedb88320 & v15
		v26 = v23 ^ v25
		v2 = v26
		v17 = v2 & 1
		v18 = int(v17)
		v20 = -v18
		v21 = uint32(v20)
		v15 = v21
		v23 = v2 >> 1
		v25 = 0xedb88320 & v15
		v26 = v23 ^ v25
		v2 = v26
		v17 = v2 & 1
		v18 = int(v17)
		v20 = -v18
		v21 = uint32(v20)
		v15 = v21
		v23 = v2 >> 1
		v25 = 0xedb88320 & v15
		v26 = v23 ^ v25
		v2 = v26
		v17 = v2 & 1
		v18 = int(v17)
		v20 = -v18
		v21 = uint32(v20)
		v15 = v21
		v23 = v2 >> 1
		v25 = 0xedb88320 & v15
		v26 = v23 ^ v25
		v2 = v26
		v17 = v2 & 1
		v18 = int(v17)
		v20 = -v18
		v21 = uint32(v20)
		v15 = v21
		v23 = v2 >> 1
		v25 = 0xedb88320 & v15
		v26 = v23 ^ v25
		v2 = v26
		v4 = v4 + 1
	}
	return ^v2
}

