// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package fnv1a_64

func Fnv1a_64(data []byte, len_ uint64) uint64 {
	var v2 uint64
	var v4 uint64
	v2 = 0xcbf29ce484222325
	v4 = 0
	for v4+7 < len_ {
		v2 = (v2 ^ uint64(data[int(v4)+0])) * 0x100000001b3
		v2 = (v2 ^ uint64(data[int(v4)+1])) * 0x100000001b3
		v2 = (v2 ^ uint64(data[int(v4)+2])) * 0x100000001b3
		v2 = (v2 ^ uint64(data[int(v4)+3])) * 0x100000001b3
		v2 = (v2 ^ uint64(data[int(v4)+4])) * 0x100000001b3
		v2 = (v2 ^ uint64(data[int(v4)+5])) * 0x100000001b3
		v2 = (v2 ^ uint64(data[int(v4)+6])) * 0x100000001b3
		v2 = (v2 ^ uint64(data[int(v4)+7])) * 0x100000001b3
		v4 = v4 + 8
	}
	for v4 < len_ {
		v2 = (v2 ^ uint64(data[int(v4)])) * 0x100000001b3
		v4 = v4 + 1
	}
	return v2
}

