// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package poly1305_block5

func Poly1305_block5(h []uint32, r []uint32, m []uint32) {
	var v4 uint64
	var v5 uint64
	var v6 uint64
	var v7 uint64
	var v8 uint64
	v11 := uint64(h[0])
	v14 := v11 + uint64(m[0])
	v16 := r[0]
	v20 := uint64(h[1])
	v25 := r[4]
	v26 := 5 * int(v25)
	v31 := uint64(h[2])
	v36 := r[3]
	v37 := 5 * int(v36)
	v41 := h[3]
	v42 := uint64(v41)
	v47 := r[2]
	v48 := 5 * int(v47)
	v52 := h[4]
	v53 := uint64(v52)
	v58 := r[1]
	v61 := ((((v14 * uint64(v16)) + (v20 * uint64(v26))) + (v31 * uint64(v37))) + (v42 * uint64(v48))) + (v53 * uint64(5 * int(v58)))
	v4 = ((((v14 * uint64(v58)) + (v20 * uint64(v16))) + (v31 * uint64(v26))) + (v42 * uint64(v37))) + (v53 * uint64(v48))
	v142 := uint64(v41)
	v5 = (((((v11 + uint64(m[1])) * uint64(v47)) + (v20 * uint64(v58))) + (v31 * uint64(v16))) + (v142 * uint64(v26))) + (v53 * uint64(v37))
	v200 := uint64(v52)
	v6 = (((((v11 + uint64(m[2])) * uint64(v36)) + (v20 * uint64(v47))) + (v31 * uint64(v58))) + (v142 * uint64(v16))) + (v200 * uint64(v26))
	v7 = (((((v11 + uint64(m[3])) * uint64(v25)) + (v20 * uint64(v36))) + (v31 * uint64(v47))) + (v142 * uint64(v58))) + (v200 * uint64(v16))
	v8 = v61 >> 26
	h[0] = uint32(v61) & uint32(0x3ffffff)
	v4 = v4 + v8
	v8 = v4 >> 26
	h[1] = uint32(v4) & uint32(0x3ffffff)
	v5 = v5 + v8
	v8 = v5 >> 26
	h[2] = uint32(v5) & uint32(0x3ffffff)
	v6 = v6 + v8
	v8 = v6 >> 26
	h[3] = uint32(v6) & uint32(0x3ffffff)
	v7 = v7 + v8
	v8 = v7 >> 26
	h[4] = uint32(v7) & uint32(0x3ffffff)
	h[0] = h[0] + (uint32(v8) * uint32(5))
	v296 := h[0]
	v8 = uint64(v296 >> 26)
	h[0] = v296 & uint32(0x3ffffff)
	h[1] = h[1] + uint32(v8)
}

