// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package stbi_crc_dogfood

func Stbi_crc32_dogfood(buf []byte, len_ uint64) uint32 {
	var v2 uint32
	var v4 uint32
	var v16 uint32
	var v18 uint32
	var v20 int
	var v22 uint32
	var v24 uint32
	var v25 uint32
	v2 = 0xffffffff
	v4 = 0
	for uint64(v4) < len_ {
		v2 = v2 ^ uint32(buf[int(v4)])
		v18 = v2 & 1
		v20 = -int(v18)
		v16 = uint32(v20)
		v22 = v2 >> 1
		v24 = 0xedb88320 & v16
		v25 = v22 ^ v24
		v2 = v25
		v18 = v2 & 1
		v20 = -int(v18)
		v16 = uint32(v20)
		v22 = v2 >> 1
		v24 = 0xedb88320 & v16
		v25 = v22 ^ v24
		v2 = v25
		v18 = v2 & 1
		v20 = -int(v18)
		v16 = uint32(v20)
		v22 = v2 >> 1
		v24 = 0xedb88320 & v16
		v25 = v22 ^ v24
		v2 = v25
		v18 = v2 & 1
		v20 = -int(v18)
		v16 = uint32(v20)
		v22 = v2 >> 1
		v24 = 0xedb88320 & v16
		v25 = v22 ^ v24
		v2 = v25
		v18 = v2 & 1
		v20 = -int(v18)
		v16 = uint32(v20)
		v22 = v2 >> 1
		v24 = 0xedb88320 & v16
		v25 = v22 ^ v24
		v2 = v25
		v18 = v2 & 1
		v20 = -int(v18)
		v16 = uint32(v20)
		v22 = v2 >> 1
		v24 = 0xedb88320 & v16
		v25 = v22 ^ v24
		v2 = v25
		v18 = v2 & 1
		v20 = -int(v18)
		v16 = uint32(v20)
		v22 = v2 >> 1
		v24 = 0xedb88320 & v16
		v25 = v22 ^ v24
		v2 = v25
		v18 = v2 & 1
		v20 = -int(v18)
		v16 = uint32(v20)
		v22 = v2 >> 1
		v24 = 0xedb88320 & v16
		v25 = v22 ^ v24
		v2 = v25
		v4 = v4 + 1
	}
	return ^v2
}

