package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"os/exec"
)

type CType struct {
	Name     string `json:"name"`
	Size     int    `json:"size"`
	IsSigned bool   `json:"is_signed"`
	IsScalar bool   `json:"is_scalar"`
	GoType   string `json:"go_type"`
}

type Spec struct {
	Types []CType `json:"types"`
}

func main() {
	cmd := exec.Command("cue", "export", "--out", "json", "./spec")
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("failed to run cue export: %v", err)
	}

	var spec Spec
	if err := json.Unmarshal(out.Bytes(), &spec); err != nil {
		log.Fatalf("failed to unmarshal JSON: %v", err)
	}

	fmt.Println("package rodata")
	fmt.Println("// Code generated by cuegen. DO NOT EDIT.")
	fmt.Println("var CTypes = []struct{ Name string; GoType string }{")
	for _, t := range spec.Types {
		fmt.Printf("\t{%q, %q},\n", t.Name, t.GoType)
	}
	fmt.Println("}")
}
