// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2vtparser

type C2_cell_t struct {
	Rune_ uint32
	Fg    byte
	Bg    byte
	Flags byte
	Width byte
}

type C2_vt_parser_t struct {
	State        int
	Cursor_x     int
	Cursor_y     int
	Cur_fg       int
	Cur_bg       int
	Cur_attr     int
	Width        int
	Height       int
	Prm          int
	Nparams      int
	Params       [4]int
	Pending_utf8 [4]byte
	Pending_len  int
}

func C2_grid_clear(cells []C2_cell_t, n int, fg byte, bg byte) {
	var v4 int
	var v9 *C2_cell_t
	v4 = 0
	{
		_cells := cells[:n]
		for v4 = 0; v4 < n; v4++ {
			v9 = &_cells[v4]
			v9.Rune_ = 32
			v9.Fg = fg
			v9.Bg = bg
			v9.Flags = 0
			v9.Width = 1
		}
	}
}

func C2_grid_clear_row(cells []C2_cell_t, y int, stride int, width int, fg byte, bg byte) {
	var v6 int
	var v15 *C2_cell_t
	for v6 = 0; v6 < width; v6++ {
		v15 = &cells[int((y*stride)+v6)]
		v15.Rune_ = 32
		v15.Fg = fg
		v15.Bg = bg
		v15.Flags = 0
		v15.Width = 1
	}
}

func C2_grid_scroll_up(cells []C2_cell_t, width int, height int, stride int, nlines int) {
	var v5 int
	var v6 int
	var v23 *C2_cell_t
	var v26 *C2_cell_t
	if nlines < 1 {
		return
	}
	if nlines > height {
		nlines = height
	}
	v12 := height - nlines
	for v5 = 0; v5 < v12; v5++ {
		v6 = 0
		for v6 < width {
			v23 = &cells[int(((v5+nlines)*stride)+v6)]
			v26 = &cells[int((v5*stride)+v6)]
			v26.Rune_ = v23.Rune_
			v26.Fg = v23.Fg
			v26.Bg = v23.Bg
			v26.Flags = v23.Flags
			v26.Width = v23.Width
			v6++
		}
	}
	for v5 = v12; v5 < height; v5++ {
		C2_grid_clear_row(cells, v5, stride, width, uint8(0), uint8(0))
	}
}

func C2_vt_init(p *C2_vt_parser_t, width int, height int) {
	p.State = 0
	p.Cursor_x = 0
	p.Cursor_y = 0
	p.Cur_fg = 0
	p.Cur_bg = 0
	p.Cur_attr = 0
	p.Width = width
	p.Height = height
	p.Prm = 0
	p.Nparams = 0
	p.Pending_len = 0
}

func C2_vt_put(p *C2_vt_parser_t, cells []C2_cell_t, r uint32) {
	var v3 int
	var v5 int
	_ = 0
	v3 = p.Width
	v5 = p.Height
	v9 := func() uint32 {
		if v3 <= 0 {
			return 1
		}
		return 0
	}()
	v11 := func() uint32 {
		if v5 <= 0 {
			return 1
		}
		return 0
	}()
	v12 := func() uint32 {
		if (v9 != 0) || (v11 != 0) {
			return 1
		}
		return 0
	}()
	if v12 != 0 {
		return
	}
	if p.Cursor_x >= v3 {
		p.Cursor_x = 0
		p.Cursor_y++
	}
	if p.Cursor_y >= v5 {
		p.Cursor_y = v5 - 1
	}
	v27 := &cells[int((p.Cursor_y*v3)+p.Cursor_x)]
	v27.Rune_ = r
	v27.Fg = byte(p.Cur_fg)
	v27.Bg = byte(p.Cur_bg)
	v27.Flags = byte(p.Cur_attr)
	v27.Width = 1
	p.Cursor_x++
}

func C2_vt_add_digit(p *C2_vt_parser_t, b byte) {
	var v2 int
	var v6 int
	v2 = int(b)
	v2 -= 48
	v6 = p.Prm
	v6 *= 10
	v6 += v2
	if v6 > 0x270f {
		v6 = 0x270f
	}
	p.Prm = v6
}

func C2_vt_finish_prm(p *C2_vt_parser_t) {
	_ = 0
	if p.Nparams < 4 {
		p.Params[p.Nparams] = p.Prm
		p.Nparams++
	}
	p.Prm = 0
}

func C2_vt_param(p *C2_vt_parser_t, i int, def int) int {
	_ = 0
	v6 := func() int {
		if i < p.Nparams {
			return 1
		}
		return 0
	}()
	v10 := func() int {
		if p.Params[i] != 0 {
			return 1
		}
		return 0
	}()
	v11 := func() int {
		if (v6 != 0) && (v10 != 0) {
			return 1
		}
		return 0
	}()
	if v11 != 0 {
		return p.Params[i]
	}
	return def
}

func C2_vt_sgr(p *C2_vt_parser_t) {
	var v1 int
	var v10 int
	var v28 int
	var v30 int
	var v31 int
	var v35 int
	var v37 int
	var v38 int
	_ = 0
	for v1 = 0; v1 < p.Nparams; v1++ {
		v10 = p.Params[v1]
		if v10 == 0 {
			p.Cur_fg = 0
			p.Cur_bg = 0
			p.Cur_attr = 0
		}
		if v10 == 1 {
			p.Cur_attr |= 1
		}
		if v10 == 4 {
			p.Cur_attr |= 4
		}
		if v10 == 7 {
			p.Cur_attr |= 8
		}
		v28 = func() int {
			if v10 >= 30 {
				return 1
			}
			return 0
		}()
		v30 = func() int {
			if v10 <= 37 {
				return 1
			}
			return 0
		}()
		v31 = func() int {
			if (v28 != 0) && (v30 != 0) {
				return 1
			}
			return 0
		}()
		if v31 != 0 {
			p.Cur_fg = v10 - 30
		}
		v35 = func() int {
			if v10 >= 40 {
				return 1
			}
			return 0
		}()
		v37 = func() int {
			if v10 <= 47 {
				return 1
			}
			return 0
		}()
		v38 = func() int {
			if (v35 != 0) && (v37 != 0) {
				return 1
			}
			return 0
		}()
		if v38 != 0 {
			p.Cur_bg = v10 - 40
		}
	}
}

func C2_vt_clear_span(cells []C2_cell_t, i0 int, i1 int, fg byte, bg byte) {
	var v11 *C2_cell_t
	for i0 < i1 {
		v11 = &cells[i0]
		v11.Rune_ = 32
		v11.Fg = fg
		v11.Bg = bg
		v11.Flags = 0
		v11.Width = 1
		i0++
	}
}

func C2_vt_csi(p *C2_vt_parser_t, cells []C2_cell_t, b byte) {
	var v3 int
	var v4 int
	var v5 int
	var v6 int
	var v37 int
	var v40 int
	var v41 int
	var v47 int
	var v50 int
	var v51 int
	var v72 int
	var v75 int
	var v76 int
	var v88 int
	var v91 int
	var v92 int
	_ = 0
	C2_vt_finish_prm(p)
	v4 = p.Width
	v5 = p.Height
	v11 := func() int {
		if b == 'H' {
			return 1
		}
		return 0
	}()
	v13 := func() int {
		if b == 'f' {
			return 1
		}
		return 0
	}()
	v14 := func() int {
		if (v11 != 0) || (v13 != 0) {
			return 1
		}
		return 0
	}()
	if v14 != 0 {
		p.Cursor_y = C2_vt_param(p, 0, 1) - 1
		p.Cursor_x = C2_vt_param(p, 1, 1) - 1
		if p.Cursor_y < 0 {
			p.Cursor_y = 0
		}
		if p.Cursor_x < 0 {
			p.Cursor_x = 0
		}
		v37 = func() int {
			if p.Height > 0 {
				return 1
			}
			return 0
		}()
		v40 = func() int {
			if p.Cursor_y >= p.Height {
				return 1
			}
			return 0
		}()
		v41 = func() int {
			if (v37 != 0) && (v40 != 0) {
				return 1
			}
			return 0
		}()
		if v41 != 0 {
			p.Cursor_y = p.Height - 1
		}
		v47 = func() int {
			if p.Width > 0 {
				return 1
			}
			return 0
		}()
		v50 = func() int {
			if p.Cursor_x >= p.Width {
				return 1
			}
			return 0
		}()
		v51 = func() int {
			if (v47 != 0) && (v50 != 0) {
				return 1
			}
			return 0
		}()
		if v51 != 0 {
			p.Cursor_x = p.Width - 1
		}
	}
	if b == 'A' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_y -= v3
		if p.Cursor_y < 0 {
			p.Cursor_y = 0
		}
	}
	if b == 'B' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_y += v3
		v72 = func() int {
			if p.Height > 0 {
				return 1
			}
			return 0
		}()
		v75 = func() int {
			if p.Cursor_y >= p.Height {
				return 1
			}
			return 0
		}()
		v76 = func() int {
			if (v72 != 0) && (v75 != 0) {
				return 1
			}
			return 0
		}()
		if v76 != 0 {
			p.Cursor_y = p.Height - 1
		}
	}
	if b == 'C' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_x += v3
		v88 = func() int {
			if p.Width > 0 {
				return 1
			}
			return 0
		}()
		v91 = func() int {
			if p.Cursor_x >= p.Width {
				return 1
			}
			return 0
		}()
		v92 = func() int {
			if (v88 != 0) && (v91 != 0) {
				return 1
			}
			return 0
		}()
		if v92 != 0 {
			p.Cursor_x = p.Width - 1
		}
	}
	if b == 'D' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_x -= v3
		if p.Cursor_x < 0 {
			p.Cursor_x = 0
		}
	}
	if b == 'm' {
		C2_vt_sgr(p)
	}
	if b == 'J' {
		v3 = C2_vt_param(p, 0, 0)
		v6 = (p.Cursor_y * v4) + p.Cursor_x
		if v3 == 0 {
			C2_vt_clear_span(cells, v6, (v4 * v5), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 1 {
			C2_vt_clear_span(cells, 0, (v6 + 1), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 2 {
			C2_vt_clear_span(cells, 0, (v4 * v5), byte(p.Cur_fg), byte(p.Cur_bg))
		}
	}
	if b == 'K' {
		v3 = C2_vt_param(p, 0, 0)
		v6 = p.Cursor_y * v4
		if v3 == 0 {
			C2_vt_clear_span(cells, (v6 + p.Cursor_x), (v6 + v4), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 1 {
			C2_vt_clear_span(cells, v6, ((v6 + p.Cursor_x) + 1), byte(p.Cur_fg), byte(p.Cur_bg))
		}
		if v3 == 2 {
			C2_vt_clear_span(cells, v6, (v6 + v4), byte(p.Cur_fg), byte(p.Cur_bg))
		}
	}
	p.State = 0
}

func C2_vt_feed_byte(p *C2_vt_parser_t, cells []C2_cell_t, b byte) int {
	var v10 *C2_cell_t
	var v25 int
	var v27 int
	var v28 int
	var v42 int
	var v44 int
	var v45 int
	var v52 int
	var v54 int
	var v55 int
	var v59 int
	var v61 int
	var v62 int
	_ = 0
	if p.Height < 0 {
		v10 = &cells[0]
		v10.Rune_ = 0
	}
	switch p.State {
	case 0:
		if b == 27 {
			p.State = 1
			return 0
		}
		if b == 10 {
			p.Cursor_y++
			p.Cursor_x = 0
			return 1
		}
		if b == 13 {
			p.Cursor_x = 0
			return 1
		}
		v25 = func() int {
			if b >= 32 {
				return 1
			}
			return 0
		}()
		v27 = func() int {
			if b <= 0x7e {
				return 1
			}
			return 0
		}()
		v28 = func() int {
			if (v25 != 0) && (v27 != 0) {
				return 1
			}
			return 0
		}()
		if v28 != 0 {
			C2_vt_put(p, cells, uint32(b))
			return 1
		}
	case 1:
		if b == 0x5b {
			p.State = 2
			p.Prm = 0
			p.Nparams = 0
			return 0
		}
		if b == 0x5d {
			p.State = 3
			return 0
		}
		p.State = 0
	case 2:
		v42 = func() int {
			if b >= '0' {
				return 1
			}
			return 0
		}()
		v44 = func() int {
			if b <= '9' {
				return 1
			}
			return 0
		}()
		v45 = func() int {
			if (v42 != 0) && (v44 != 0) {
				return 1
			}
			return 0
		}()
		if v45 != 0 {
			C2_vt_add_digit(p, b)
			return 0
		}
		if b == ';' {
			C2_vt_finish_prm(p)
			return 0
		}
		v52 = func() int {
			if b >= 64 {
				return 1
			}
			return 0
		}()
		v54 = func() int {
			if b <= 0x7e {
				return 1
			}
			return 0
		}()
		v55 = func() int {
			if (v52 != 0) && (v54 != 0) {
				return 1
			}
			return 0
		}()
		if v55 != 0 {
			C2_vt_csi(p, cells, b)
			return 0
		}
	case 3:
		v59 = func() int {
			if b == 7 {
				return 1
			}
			return 0
		}()
		v61 = func() int {
			if b == 27 {
				return 1
			}
			return 0
		}()
		v62 = func() int {
			if (v59 != 0) || (v61 != 0) {
				return 1
			}
			return 0
		}()
		if v62 != 0 {
			p.State = 0
			return 0
		}
	}
	return 0
}
