// Package emit — passe 5 de p2go : génération de source Go 1.27 typé depuis
// l'IR. Les slots redeviennent des variables Go nommées (noms PHP assainis,
// aucun map ni any) ; les locales sont hoistées en tête de fonction (portée
// PHP = fonction entière).
package emit

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"code.hazyhaar.fr/devhoros/c2simd/p2go/ir"
	"code.hazyhaar.fr/devhoros/c2simd/p2go/types"
)

var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
	"main": true, "fmt": true, "int64": true, "true": true, "false": true,
	// identifiants réservés des helpers générés
	"p2goSumI64": true, "p2goSumI64Scalar": true,
}

// EmitFiles génère le programme Go complet : "main.go" toujours ; si une
// boucle de réduction SumLoop est présente, deux fichiers helpers duals
// s'ajoutent — scalaire (!goexperiment.simd) et vectorisé simd/archsimd
// (goexperiment.simd, garde runtime AVX2, queue scalaire).
func EmitFiles(prog *ir.Program, srcName string) map[string]string {
	e := &emitter{helpers: map[string]bool{}, simd: map[string]bool{}}
	e.funcNames = map[string]string{}
	for _, f := range prog.Funcs {
		e.funcNames[f.Name] = safeName(f.Name, nil)
	}
	var body strings.Builder
	for _, f := range prog.Funcs {
		e.emitFunc(&body, f)
		body.WriteString("\n")
	}
	e.emitFunc(&body, prog.Main)

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by p2go v0.1.0 from %s. DO NOT EDIT.\n", srcName)
	b.WriteString("package main\n\n")
	var imports []string
	if usesEcho(prog) {
		imports = append(imports, "fmt")
	}
	if e.needStrconv {
		imports = append(imports, "strconv")
	}
	if e.needStrings {
		imports = append(imports, "strings")
	}
	switch len(imports) {
	case 0:
	case 1:
		fmt.Fprintf(&b, "import %q\n\n", imports[0])
	default:
		b.WriteString("import (\n")
		for _, im := range imports {
			fmt.Fprintf(&b, "\t%q\n", im)
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(body.String())

	// Helpers builtins requis, en ordre stable.
	var hnames []string
	for h := range e.helpers {
		hnames = append(hnames, h)
	}
	sort.Strings(hnames)
	for _, h := range hnames {
		b.WriteString("\n" + helperSrc[h])
	}

	files := map[string]string{}
	if len(e.simd) > 0 {
		var keys []string
		for k := range e.simd {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		var off, on strings.Builder
		fmt.Fprintf(&off, simdFileHeader, "!goexperiment.simd")
		fmt.Fprintf(&on, simdFileHeader, "goexperiment.simd")
		on.WriteString("\nimport \"simd/archsimd\"\n")
		for _, k := range keys {
			h := simdHelpers[k]
			b.WriteString("\n" + h.core)
			off.WriteString("\n" + h.off)
			on.WriteString("\n" + h.on)
		}
		files["p2go_simd_off.go"] = off.String()
		files["p2go_simd_on.go"] = on.String()
	}
	files["main.go"] = b.String()
	return files
}

// Emit conserve l'API mono-fichier (programmes sans réduction SIMD).
func Emit(prog *ir.Program, srcName string) string {
	return EmitFiles(prog, srcName)["main.go"]
}

func usesEcho(prog *ir.Program) bool {
	found := false
	var walk func(body []ir.Stmt)
	walk = func(body []ir.Stmt) {
		for _, st := range body {
			switch s := st.(type) {
			case *ir.Echo:
				found = true
			case *ir.If:
				walk(s.Then)
				walk(s.Else)
			case *ir.While:
				walk(s.Body)
			case *ir.For:
				walk(s.Body)
			case *ir.Switch:
				for _, c := range s.Cases {
					walk(c.Body)
				}
				walk(s.Default)
			}
		}
	}
	for _, f := range prog.Funcs {
		walk(f.Body)
	}
	walk(prog.Main.Body)
	return found
}

type emitter struct {
	funcNames   map[string]string // nom IR → identifiant Go
	slotNames   []string          // fonction courante : slot → identifiant Go
	needStrconv bool              // une conversion ItoS a été émise
	needStrings bool              // str_replace/trim → import strings
	helpers     map[string]bool   // helpers p2go* requis (builtins)
	simd        map[string]bool   // helpers duals scalaire/archsimd requis (simd.go)
}

// goType — type Go d'un kind de slot.
func goType(k types.SlotKind) string {
	switch k {
	case types.KindArr:
		return "[]int64"
	case types.KindStr:
		return "string"
	}
	return "int64"
}

func safeName(name string, taken map[string]bool) string {
	n := name
	if strings.HasPrefix(n, "p2go") { // espace réservé aux helpers et gensyms émis
		n = "u_" + n
	}
	for goKeywords[n] || (taken != nil && taken[n]) {
		n += "_"
	}
	return n
}

func (e *emitter) emitFunc(b *strings.Builder, f *ir.Func) {
	// Noms Go des slots : nom PHP, désambiguïsé des keywords, des noms de
	// fonctions du programme (une locale homonyme masquerait l'appel) et des
	// autres slots.
	taken := map[string]bool{}
	for _, gn := range e.funcNames {
		taken[gn] = true
	}
	e.slotNames = make([]string, len(f.SlotNames))
	for i, n := range f.SlotNames {
		gn := safeName(n, taken)
		taken[gn] = true
		e.slotNames[i] = gn
	}

	if f.Name == "main" {
		b.WriteString("func main() {\n")
	} else {
		var params []string
		for i := 0; i < f.Params; i++ {
			params = append(params, e.slotNames[i]+" "+goType(f.SlotKinds[i]))
		}
		ret := ""
		if f.ReturnsValue {
			ret = " " + goType(f.ReturnKind)
		}
		fmt.Fprintf(b, "func %s(%s)%s {\n", e.funcNames[f.Name], strings.Join(params, ", "), ret)
	}

	// Locales hoistées (portée fonction, sémantique PHP), par kind de slot.
	var ints, arrs, strs []string
	for i := f.Params; i < len(f.SlotNames); i++ {
		switch f.SlotKinds[i] {
		case types.KindArr:
			arrs = append(arrs, e.slotNames[i])
		case types.KindStr:
			strs = append(strs, e.slotNames[i])
		default:
			ints = append(ints, e.slotNames[i])
		}
	}
	if len(ints) > 0 {
		fmt.Fprintf(b, "\tvar %s int64\n", strings.Join(ints, ", "))
	}
	if len(arrs) > 0 {
		fmt.Fprintf(b, "\tvar %s []int64\n", strings.Join(arrs, ", "))
	}
	if len(strs) > 0 {
		fmt.Fprintf(b, "\tvar %s string\n", strings.Join(strs, ", "))
	}

	e.emitStmts(b, f.Body, 1)

	// Un slot écrit mais jamais lu déclencherait « declared and not used ».
	reads := map[int]bool{}
	collectReads(f.Body, reads)
	var unread []string
	for i := f.Params; i < len(f.SlotNames); i++ {
		if !reads[i] {
			unread = append(unread, "_ = "+e.slotNames[i])
		}
	}
	if len(unread) > 0 {
		fmt.Fprintf(b, "\t%s\n", strings.Join(unread, "; "))
	}
	b.WriteString("}\n")
}

func collectReads(body []ir.Stmt, reads map[int]bool) {
	var walkE func(ir.Expr)
	walkE = func(x ir.Expr) {
		switch v := x.(type) {
		case *ir.Slot:
			reads[v.Index] = true
		case *ir.Bin:
			walkE(v.L)
			walkE(v.R)
		case *ir.Logic:
			walkE(v.L)
			walkE(v.R)
		case *ir.Not:
			walkE(v.X)
		case *ir.Neg:
			walkE(v.X)
		case *ir.BitNot:
			walkE(v.X)
		case *ir.Call:
			for _, a := range v.Args {
				walkE(a)
			}
		case *ir.Index:
			reads[v.Slot] = true
			walkE(v.Idx)
		case *ir.Count:
			reads[v.Slot] = true
		case *ir.ItoS:
			walkE(v.X)
		case *ir.StrLen:
			walkE(v.X)
		case *ir.ArrCopy:
			walkE(v.X)
		case *ir.ArrLit:
			for _, el := range v.Elems {
				walkE(el)
			}
		case *ir.Builtin:
			for _, a := range v.Args {
				walkE(a)
			}
		}
	}
	var walkS func([]ir.Stmt)
	walkS = func(stmts []ir.Stmt) {
		for _, st := range stmts {
			switch s := st.(type) {
			case *ir.Assign:
				walkE(s.Expr)
			case *ir.Echo:
				for _, a := range s.Args {
					walkE(a)
				}
			case *ir.If:
				walkE(s.Cond)
				walkS(s.Then)
				walkS(s.Else)
			case *ir.While:
				walkE(s.Cond)
				walkS(s.Body)
			case *ir.For:
				if s.Init != nil {
					walkS([]ir.Stmt{s.Init})
				}
				if s.Cond != nil {
					walkE(s.Cond)
				}
				if s.Post != nil {
					walkS([]ir.Stmt{s.Post})
				}
				walkS(s.Body)
			case *ir.Return:
				if s.Expr != nil {
					walkE(s.Expr)
				}
			case *ir.CallStmt:
				for _, a := range s.Call.Args {
					walkE(a)
				}
			case *ir.ArrAssign:
				for _, el := range s.Elems {
					walkE(el)
				}
			case *ir.IndexAssign:
				// a[i] = e compte comme usage Go du slot tableau.
				reads[s.Slot] = true
				walkE(s.Idx)
				walkE(s.Expr)
			case *ir.SumLoop:
				reads[s.Acc] = true
				reads[s.Arr] = true
			case *ir.DotLoop:
				reads[s.Acc] = true
				reads[s.A] = true
				reads[s.B] = true
			case *ir.MinMaxLoop:
				reads[s.Dst] = true
				reads[s.Arr] = true
			case *ir.Switch:
				walkE(s.Subject)
				for _, c := range s.Cases {
					for _, v := range c.Vals {
						walkE(v)
					}
					walkS(c.Body)
				}
				walkS(s.Default)
			case *ir.ArrPush:
				reads[s.Slot] = true
				walkE(s.Val)
			case *ir.ArrPop:
				reads[s.Arr] = true
			}
		}
	}
	walkS(body)
}

func (e *emitter) emitStmts(b *strings.Builder, body []ir.Stmt, depth int) {
	ind := strings.Repeat("\t", depth)
	for _, st := range body {
		switch s := st.(type) {
		case *ir.Assign:
			fmt.Fprintf(b, "%s%s = %s\n", ind, e.slotNames[s.Slot], e.expr(s.Expr, 0))
		case *ir.Echo:
			for _, a := range s.Args {
				if str, ok := a.(*ir.Str); ok {
					fmt.Fprintf(b, "%sfmt.Print(%s)\n", ind, strconv.Quote(str.Value))
					continue
				}
				fmt.Fprintf(b, "%sfmt.Print(%s)\n", ind, e.expr(a, 0))
			}
		case *ir.If:
			fmt.Fprintf(b, "%sif %s {\n", ind, e.expr(s.Cond, 0))
			e.emitStmts(b, s.Then, depth+1)
			if len(s.Else) > 0 {
				fmt.Fprintf(b, "%s} else {\n", ind)
				e.emitStmts(b, s.Else, depth+1)
			}
			fmt.Fprintf(b, "%s}\n", ind)
		case *ir.While:
			fmt.Fprintf(b, "%sfor %s {\n", ind, e.expr(s.Cond, 0))
			e.emitStmts(b, s.Body, depth+1)
			fmt.Fprintf(b, "%s}\n", ind)
		case *ir.For:
			init, cond, post := "", "", ""
			if a, ok := s.Init.(*ir.Assign); ok {
				init = fmt.Sprintf("%s = %s", e.slotNames[a.Slot], e.expr(a.Expr, 0))
			}
			if s.Cond != nil {
				cond = e.expr(s.Cond, 0)
			}
			if a, ok := s.Post.(*ir.Assign); ok {
				post = fmt.Sprintf("%s = %s", e.slotNames[a.Slot], e.expr(a.Expr, 0))
			}
			fmt.Fprintf(b, "%sfor %s; %s; %s {\n", ind, init, cond, post)
			e.emitStmts(b, s.Body, depth+1)
			fmt.Fprintf(b, "%s}\n", ind)
		case *ir.Return:
			if s.Expr != nil {
				fmt.Fprintf(b, "%sreturn %s\n", ind, e.expr(s.Expr, 0))
			} else {
				fmt.Fprintf(b, "%sreturn\n", ind)
			}
		case *ir.CallStmt:
			fmt.Fprintf(b, "%s%s\n", ind, e.call(s.Call))
		case *ir.ArrAssign:
			var elems []string
			for _, el := range s.Elems {
				elems = append(elems, e.expr(el, 0))
			}
			fmt.Fprintf(b, "%s%s = []int64{%s}\n", ind, e.slotNames[s.Slot], strings.Join(elems, ", "))
		case *ir.IndexAssign:
			fmt.Fprintf(b, "%s%s[%s] = %s\n", ind, e.slotNames[s.Slot], e.expr(s.Idx, 0), e.expr(s.Expr, 0))
		case *ir.SumLoop:
			e.simd["sum"] = true
			fmt.Fprintf(b, "%s%s += p2goSumI64(%s)\n", ind, e.slotNames[s.Acc], e.slotNames[s.Arr])
		case *ir.DotLoop:
			e.simd["dot"] = true
			fmt.Fprintf(b, "%s%s += p2goDotI64(%s, %s)\n", ind, e.slotNames[s.Acc], e.slotNames[s.A], e.slotNames[s.B])
		case *ir.MinMaxLoop:
			h := "p2goMinI64"
			if s.IsMax {
				h = "p2goMaxI64"
				e.simd["max"] = true
			} else {
				e.simd["min"] = true
			}
			d := e.slotNames[s.Dst]
			fmt.Fprintf(b, "%s%s = %s(%s, %s)\n", ind, d, h, d, e.slotNames[s.Arr])
		case *ir.ArrPush:
			a := e.slotNames[s.Slot]
			fmt.Fprintf(b, "%s%s = append(%s, %s)\n", ind, a, a, e.expr(s.Val, 0))
		case *ir.ArrPop:
			a := e.slotNames[s.Arr]
			fmt.Fprintf(b, "%s%s = %s[len(%s)-1]\n", ind, e.slotNames[s.Dst], a, a)
			fmt.Fprintf(b, "%s%s = %s[:len(%s)-1]\n", ind, a, a, a)
		case *ir.Break:
			fmt.Fprintf(b, "%sbreak\n", ind)
		case *ir.Continue:
			fmt.Fprintf(b, "%scontinue\n", ind)
		case *ir.Switch:
			fmt.Fprintf(b, "%sswitch %s {\n", ind, e.expr(s.Subject, 0))
			for _, c := range s.Cases {
				var vals []string
				for _, v := range c.Vals {
					vals = append(vals, e.expr(v, 0))
				}
				fmt.Fprintf(b, "%scase %s:\n", ind, strings.Join(vals, ", "))
				e.emitStmts(b, c.Body, depth+1)
			}
			if s.Default != nil {
				fmt.Fprintf(b, "%sdefault:\n", ind)
				e.emitStmts(b, s.Default, depth+1)
			}
			fmt.Fprintf(b, "%s}\n", ind)
		}
	}
}

// Précédences Go (extrait suffisant au subset) : plus haut lie plus fort.
func prec(op string) int {
	switch op {
	case "||":
		return 1
	case "&&":
		return 2
	case "==", "!=", "<", "<=", ">", ">=":
		return 3
	case "+", "-", "|", "^":
		return 4
	case "*", "/", "%", "<<", ">>", "&":
		return 5
	}
	return 0
}

func (e *emitter) expr(x ir.Expr, parent int) string {
	switch v := x.(type) {
	case *ir.Const:
		if v.Value < 0 && parent > 0 {
			return "(" + strconv.FormatInt(v.Value, 10) + ")"
		}
		return strconv.FormatInt(v.Value, 10)
	case *ir.Slot:
		return e.slotNames[v.Index]
	case *ir.Neg:
		return "-" + e.expr(v.X, 6)
	case *ir.Not:
		return "!" + e.expr(v.X, 6)
	case *ir.BitNot:
		return "^" + e.expr(v.X, 6)
	case *ir.Bin:
		op := v.Op
		if op == "." { // concaténation PHP → + Go sur strings
			op = "+"
		}
		p := prec(op)
		s := e.expr(v.L, p) + " " + op + " " + e.expr(v.R, p+1)
		if p < parent {
			return "(" + s + ")"
		}
		return s
	case *ir.Logic:
		p := prec(v.Op)
		s := e.expr(v.L, p) + " " + v.Op + " " + e.expr(v.R, p+1)
		if p < parent {
			return "(" + s + ")"
		}
		return s
	case *ir.Call:
		return e.call(v)
	case *ir.Index:
		return e.slotNames[v.Slot] + "[" + e.expr(v.Idx, 0) + "]"
	case *ir.Count:
		return "int64(len(" + e.slotNames[v.Slot] + "))"
	case *ir.ItoS:
		e.needStrconv = true
		return "strconv.FormatInt(" + e.expr(v.X, 0) + ", 10)"
	case *ir.StrLen:
		return "int64(len(" + e.expr(v.X, 0) + "))"
	case *ir.ArrCopy:
		return "append([]int64(nil), " + e.expr(v.X, 0) + "...)"
	case *ir.Builtin:
		return e.builtin(v)
	case *ir.ArrLit:
		var elems []string
		for _, el := range v.Elems {
			elems = append(elems, e.expr(el, 0))
		}
		return "[]int64{" + strings.Join(elems, ", ") + "}"
	case *ir.Str:
		return strconv.Quote(v.Value)
	}
	panic("emit: expression IR inconnue")
}

func (e *emitter) call(c *ir.Call) string {
	var args []string
	for _, a := range c.Args {
		args = append(args, e.expr(a, 0))
	}
	return e.funcNames[c.Name] + "(" + strings.Join(args, ", ") + ")"
}
