package sgoiter_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"code.hazyhaar.fr/devhoros/c2simd/sgoiter/emit"
	"code.hazyhaar.fr/devhoros/c2simd/sgoiter/front"
	"code.hazyhaar.fr/devhoros/c2simd/sgoiter/rules"
)

// TestExtraLibsDogfoodKATs — runtime KATs for the 4 extra-libs dogfood kernels
// (cjson_number, yyjson_digit, utf8_iterate, stbi_crc). Emit through the real
// front+rules+emit pipeline, then compare against C-known vectors.
func TestExtraLibsDogfoodKATs(t *testing.T) {
	srcRoot := filepath.Join("..", "spec", "c_sources", "testdata", "c_sources")
	kernels := []struct {
		file string
	}{
		{"cjson_number_dogfood.c"},
		{"yyjson_digit_dogfood.c"},
		{"utf8_iterate_dogfood.c"},
		{"stbi_crc_dogfood.c"},
	}
	dir := t.TempDir()
	var parts []string
	for _, k := range kernels {
		cpath, err := filepath.Abs(filepath.Join(srcRoot, k.file))
		if err != nil {
			t.Fatal(err)
		}
		m, err := front.ParseFile(cpath)
		if err != nil {
			t.Fatalf("parse %s: %v", k.file, err)
		}
		m, err = rules.ApplyAll(m)
		if err != nil {
			t.Fatalf("rules %s: %v", k.file, err)
		}
		m.Name = "extra"
		src, err := emit.Emit(m, emit.ProfileGo127)
		if err != nil {
			t.Fatalf("emit %s: %v", k.file, err)
		}
		parts = append(parts, stripImports(splitPkg(src)))
	}
	combined := "// Code generated by sgoiter extra dogfood KAT; DO NOT EDIT.\npackage extra\n\n"
	for _, p := range parts {
		combined += p + "\n"
	}
	if err := os.WriteFile(filepath.Join(dir, "extra.go"), []byte(combined), 0o644); err != nil {
		t.Fatal(err)
	}
	testGo := `package extra

import "testing"

func TestCjsonParseU64(t *testing.T) {
	type v struct {
		s        string
		wantV    uint64
		wantCons uint64
	}
	// oracle: gcc on the same C source; values computed with python reference
	vecs := []v{
		{"42", 42, 2},
		{"", 0, 0},
		{"42X", 42, 2},
		{"0123456789abcdefX", 123456789, 10},
		{"0", 0, 1},
		{"184467440737095516", 184467440737095516, 18},
		{"9999999999999999999", 9999999999999999999, 19},
		{"1234567890", 1234567890, 10},
	}
	for _, tc := range vecs {
		var nc uint64
		got := Cjson_parse_u64_dogfood([]byte(tc.s), uint64(len(tc.s)), &nc)
		if got != tc.wantV || nc != tc.wantCons {
			t.Errorf("parse %q: got (%d,%d) want (%d,%d)", tc.s, got, nc, tc.wantV, tc.wantCons)
		}
	}
	// null input: value 0, *nconsumed reset to 0
	var nc uint64 = 77
	if got := Cjson_parse_u64_dogfood(nil, 0, &nc); got != 0 || nc != 0 {
		t.Errorf("nil: got (%d,%d) want (0,0)", got, nc)
	}
}

func TestCjsonIsNullLit(t *testing.T) {
	type v struct{ s string; want uint64 }
	vecs := []v{
		{"null", 1},
		{"nullx", 1},
		{"nu", 0},
		{"", 0},
		{"NULL", 0},
		{"nulx", 0},
	}
	for _, tc := range vecs {
		got := Cjson_is_null_lit_dogfood([]byte(tc.s), uint64(len(tc.s)))
		if got != tc.want {
			t.Errorf("null-lit %q: got %d want %d", tc.s, got, tc.want)
		}
	}
	if got := Cjson_is_null_lit_dogfood(nil, 0); got != 0 {
		t.Errorf("nil: got %d want 0", got)
	}
}

func TestYyjsonCountDigits(t *testing.T) {
	type v struct{ s string; want uint64 }
	vecs := []v{
		{"42abc", 2},
		{"", 0},
		{"abc", 0},
		{"0123456789", 10},
		{"9x", 1},
		{"42 7", 2},
	}
	for _, tc := range vecs {
		got := Yyjson_count_digits_dogfood([]byte(tc.s), uint64(len(tc.s)))
		if got != tc.want {
			t.Errorf("count-digits %q: got %d want %d", tc.s, got, tc.want)
		}
	}
	if got := Yyjson_count_digits_dogfood(nil, 0); got != 0 {
		t.Errorf("nil: got %d want 0", got)
	}
}

func TestYyjsonSkipWS(t *testing.T) {
	type v struct{ s string; want uint64 }
	vecs := []v{
		{"  X", 2},
		{" \t\n\rX", 4},
		{"X", 0},
		{"", 0},
		{"   ", 3},
		{"\tX", 1},
		{"\r\n 42", 3},
	}
	for _, tc := range vecs {
		got := Yyjson_skip_ws_dogfood([]byte(tc.s), uint64(len(tc.s)))
		if got != tc.want {
			t.Errorf("skip-ws %q: got %d want %d", tc.s, got, tc.want)
		}
	}
	if got := Yyjson_skip_ws_dogfood(nil, 0); got != 0 {
		t.Errorf("nil: got %d want 0", got)
	}
}

func TestUtf8Cl(t *testing.T) {
	type v struct{ c uint8; want uint64 }
	vecs := []v{
		{0x00, 1}, {0x41, 1}, {0x7f, 1},
		{0xc2, 2}, {0xdf, 2},
		{0xe0, 3}, {0xef, 3},
		{0xf0, 4}, {0xf7, 4},
		{0x80, 0}, {0xff, 0},
	}
	for _, tc := range vecs {
		got := Utf8_cl_dogfood(tc.c)
		if got != tc.want {
			t.Errorf("cl 0x%02x: got %d want %d", tc.c, got, tc.want)
		}
	}
}

func TestUtf8Iterate2(t *testing.T) {
	type v struct{ s []byte; want uint64 }
	vecs := []v{
		{[]byte{0x41}, 0x100000041},
		{[]byte{0x41, 0x42}, 0x100000041},
		{[]byte{0xc3, 0xa9}, 0x2000000e9}, // é = U+00E9
		{[]byte{0xc3, 0x00}, 0xffffffff},  // bad continuation
		{[]byte{0xc0, 0x80}, 0xffffffff},  // overlong
		{[]byte{0xe2, 0x82, 0xac}, 0xffffffff}, // 3-byte unsupported in slice
		{[]byte{}, 0xffffffff},
		{nil, 0xffffffff},
	}
	for _, tc := range vecs {
		got := Utf8_iterate2_dogfood(tc.s, uint64(len(tc.s)))
		if got != tc.want {
			t.Errorf("iterate %x: got %#x want %#x", tc.s, got, tc.want)
		}
	}
}

func TestStbiCRC32(t *testing.T) {
	type v struct{ s string; want uint32 }
	// oracle: python zlib.crc32 (standard CRC-32, poly 0xedb88320)
	vecs := []v{
		{"", 0x00000000},
		{"abc", 0x352441c2},
		{"0123456789abcdef", 0x68c4f033},
		{"0123456789abcdefX", 0x080a93ad},
		{"\x00\x01\x02\x03", 0x8bb98613},
		{"hello world", 0x0d4a1185},
	}
	for _, tc := range vecs {
		got := Stbi_crc32_dogfood([]byte(tc.s), uint64(len(tc.s)))
		if got != tc.want {
			t.Errorf("crc %q: got %#x want %#x", tc.s, got, tc.want)
		}
	}
	if got := Stbi_crc32_dogfood(nil, 0); got != 0 {
		t.Errorf("nil: got %#x want 0", got)
	}
}
`
	if err := os.WriteFile(filepath.Join(dir, "kat_test.go"), []byte(testGo), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module extra\n\ngo 1.26\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command("go", "test", "-count=1", "-v", ".")
	cmd.Dir = dir
	cmd.Env = append(os.Environ(), "GOWORK=off")
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("extra dogfood KAT: %v\n%s", err, out)
	}
	t.Logf("%s", out)
}
