package emit

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"strings"
)

// DomainFile maps logical subsystem domain names to their output filenames.
const (
	DomainTypes   = "monocypher_types.go"
	DomainUtils   = "monocypher_utils.go"
	DomainPoly    = "poly1305.go"
	DomainBlake   = "blake2b.go"
	DomainChacha  = "chacha20.go"
	DomainAEAD    = "aead.go"
	DomainFE      = "fe.go"
	DomainGE      = "ge.go"
	DomainX25519  = "curve25519.go"
	DomainEdDSA   = "eddsa.go"
)

// classifyDecl assigns an AST declaration to a logical domain file.
func classifyDecl(decl ast.Decl) string {
	switch d := decl.(type) {
	case *ast.GenDecl:
		if d.Tok == token.IMPORT {
			return ""
		}
		if d.Tok == token.TYPE {
			return DomainTypes
		}
		if d.Tok == token.VAR || d.Tok == token.CONST {
			for _, spec := range d.Specs {
				if vs, ok := spec.(*ast.ValueSpec); ok {
					for _, name := range vs.Names {
						low := strings.ToLower(name.Name)
						switch {
						case low == "zero" || low == "r" || low == "base_point":
							return DomainTypes
						case low == "fe_one" || low == "sqrtm1" || low == "d" || low == "d2" ||
							low == "lop_x" || low == "lop_y" || low == "ufactor" || low == "a2" || low == "a":
							return DomainTypes
						case strings.Contains(low, "x25519"):
							return DomainTypes
						}
					}
				}
			}
			return DomainTypes
		}
	case *ast.FuncDecl:
		fn := d.Name.Name
		low := strings.ToLower(fn)
		switch {
		case strings.HasPrefix(low, "crypto_poly1305") || strings.HasPrefix(low, "poly_"):
			return DomainPoly
		// blake2b_ (sans préfixe crypto_) : Blake2b_compress (~800 lignes)
		// tombait dans utils faute de motif — audit 2026-08-15.
		case strings.HasPrefix(low, "crypto_blake2b") || strings.HasPrefix(low, "blake2b_") ||
			strings.HasPrefix(low, "blake_") || strings.HasPrefix(low, "extended_hash"):
			return DomainBlake
		case strings.HasPrefix(low, "crypto_chacha20") || strings.HasPrefix(low, "chacha20_"):
			return DomainChacha
		case strings.HasPrefix(low, "crypto_aead") || strings.HasPrefix(low, "lock_auth"):
			return DomainAEAD
		case strings.HasPrefix(low, "fe_"):
			return DomainFE
		case strings.HasPrefix(low, "ge_"):
			return DomainGE
		case strings.HasPrefix(low, "crypto_x25519") || strings.HasPrefix(low, "scalarmult") ||
			strings.HasPrefix(low, "curve_to_") || strings.HasPrefix(low, "add_xl") ||
			strings.HasPrefix(low, "scalar_bit") || strings.HasPrefix(low, "multiply") || strings.HasPrefix(low, "redc") ||
			strings.HasPrefix(low, "crypto_elligator") || strings.HasPrefix(low, "elligator_"):
			return DomainX25519
		case strings.HasPrefix(low, "crypto_eddsa") || strings.HasPrefix(low, "slide_") ||
			strings.HasPrefix(low, "lookup_add") || strings.HasPrefix(low, "select_lop"):
			return DomainEdDSA
		case strings.HasPrefix(low, "crypto_verify") || strings.HasPrefix(low, "crypto_wipe") ||
			strings.HasPrefix(low, "gap") || strings.HasPrefix(low, "load") || strings.HasPrefix(low, "store") ||
			strings.HasPrefix(low, "copy_block") || strings.HasPrefix(low, "xor_block"):
			return DomainUtils
		default:
			return DomainUtils
		}
	}
	return DomainUtils
}

// SplitGoSource splits a monolithic generated Go file into logical modular domain files.
func SplitGoSource(src string, pkgName string) (map[string]string, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, "", src, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("split parse error: %w", err)
	}

	declsByDomain := map[string][]ast.Decl{}
	for _, decl := range node.Decls {
		dom := classifyDecl(decl)
		if dom == "" {
			continue
		}
		declsByDomain[dom] = append(declsByDomain[dom], decl)
	}

	out := map[string]string{}
	for dom, decls := range declsByDomain {
		var buf bytes.Buffer
		for _, decl := range decls {
			if err := printer.Fprint(&buf, fset, decl); err != nil {
				return nil, fmt.Errorf("print error in %s: %w", dom, err)
			}
			buf.WriteString("\n\n")
		}
		declBody := buf.String()

		// Compute required imports for this file
		var imports []string
		if strings.Contains(declBody, "binary.") {
			imports = append(imports, `"encoding/binary"`)
		}
		if strings.Contains(declBody, "bits.") {
			imports = append(imports, `"math/bits"`)
		}
		if strings.Contains(declBody, "unsafe.") {
			imports = append(imports, `"unsafe"`)
		}

		var fileBuf bytes.Buffer
		fileBuf.WriteString("// Code generated by sgoiter emit go127; DO NOT EDIT.\n")
		fmt.Fprintf(&fileBuf, "package %s\n\n", pkgName)
		if len(imports) > 0 {
			fileBuf.WriteString("import (\n")
			for _, imp := range imports {
				fmt.Fprintf(&fileBuf, "\t%s\n", imp)
			}
			fileBuf.WriteString(")\n\n")
		}
		fileBuf.WriteString(declBody)

		formatted, err := format.Source(fileBuf.Bytes())
		if err != nil {
			return nil, fmt.Errorf("gofmt error on %s: %w\nContent:\n%s", dom, err, fileBuf.String())
		}
		out[dom] = string(formatted)
	}

	return out, nil
}
