package emit

import (
	"os"
	"strings"
	"testing"
)

func TestSplitGoSource(t *testing.T) {
	sample := `
package monocypher55

import (
	"encoding/binary"
	"math/bits"
)

type Crypto_poly1305_ctx struct {
	C [16]uint8
}

var zero = [128]byte{}

func Gap(x uint64, pow_2 uint64) uint64 {
	return uint64((^x + 1) & (pow_2 - 1))
}

func Crypto_poly1305_init(ctx *Crypto_poly1305_ctx, key []byte) {
	ctx.C[0] = key[0]
}

func Crypto_chacha20_h(out []byte, key []byte, nonce []byte) {
	out[0] = key[0] ^ nonce[0]
}

func Fe_add(out []int, a []int, b []int) {
	out[0] = a[0] + b[0]
}
`
	files, err := SplitGoSource(sample, "monocypher55")
	if err != nil {
		t.Fatalf("SplitGoSource failed: %v", err)
	}

	if _, ok := files[DomainTypes]; !ok {
		t.Errorf("expected %s in output", DomainTypes)
	}
	if _, ok := files[DomainUtils]; !ok {
		t.Errorf("expected %s in output", DomainUtils)
	}
	if _, ok := files[DomainPoly]; !ok {
		t.Errorf("expected %s in output", DomainPoly)
	}
	if _, ok := files[DomainChacha]; !ok {
		t.Errorf("expected %s in output", DomainChacha)
	}
	if _, ok := files[DomainFE]; !ok {
		t.Errorf("expected %s in output", DomainFE)
	}
}

func TestSplitRealMonocypherFile(t *testing.T) {
	path := "/devhoros/pkg/monocypher55/monocypher_aead_sgoiter.go"
	content, err := os.ReadFile(path)
	if err != nil {
		t.Skipf("cannot read %s: %v", path, err)
	}
	files, err := SplitGoSource(string(content), "monocypher55")
	if err != nil {
		t.Fatalf("SplitGoSource failed on real file: %v", err)
	}

	expected := []string{
		DomainTypes,
		DomainUtils,
		DomainPoly,
		DomainBlake,
		DomainChacha,
		DomainAEAD,
		DomainFE,
		DomainGE,
		DomainX25519,
		DomainEdDSA,
	}
	for _, exp := range expected {
		code, ok := files[exp]
		if !ok {
			t.Errorf("missing expected domain file: %s", exp)
			continue
		}
		if !strings.HasPrefix(code, "// Code generated by sgoiter emit go127; DO NOT EDIT.\npackage monocypher55\n") {
			t.Errorf("invalid header in %s", exp)
		}
	}
}
