// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package adv_pointer_alias

import "unsafe"

func Adv_alias_load32(p []byte) uint32 {
	return uint32(*(*uint32)(unsafe.Pointer(&p[0])))
}

func Adv_alias_store32(p []byte, v uint32) {
	*(*uint32)(unsafe.Pointer(&p[0])) = v
}

func Adv_overlap_xor(dst []byte, src []byte, n uint64) {
	var v3 uint64
	v3 = 0
	for v3 < n {
		dst[int(v3)] = dst[int(v3)] ^ src[int(v3)]
		v3 = v3 + 1
	}
}

