// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package blake2b_compress

import (
	"math/bits"
	"unsafe"
)

var blake2b_sigma = [192]byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3, 11, 8, 12, 0, 5, 2, 15, 13, 10, 14, 3, 6, 7, 1, 9, 4, 7, 9, 3, 1, 13, 12, 11, 14, 2, 6, 5, 10, 4, 0, 15, 8, 9, 0, 5, 7, 2, 4, 10, 15, 14, 1, 11, 12, 6, 8, 3, 13, 2, 12, 6, 10, 0, 11, 8, 3, 4, 13, 7, 5, 15, 14, 1, 9, 12, 5, 1, 15, 14, 13, 4, 10, 0, 7, 6, 3, 9, 2, 8, 11, 13, 11, 7, 14, 12, 1, 3, 9, 5, 0, 15, 4, 8, 6, 2, 10, 6, 15, 14, 9, 11, 3, 0, 8, 12, 2, 13, 7, 1, 4, 10, 5, 10, 2, 8, 4, 7, 6, 1, 5, 15, 11, 9, 14, 3, 12, 13, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 14, 10, 4, 8, 9, 15, 13, 6, 1, 12, 0, 2, 11, 7, 5, 3}

func Blake2b_compress_block(h []uint64, block []byte, t0 uint64, t1 uint64, f0 uint64, f1 uint64) {
	var v9 int
	var v10 int
	var v7 [16]uint64
	var v8 [16]uint64
	v9 = 0
	for v9 < 16 {
		v7[v9] = *(*uint64)(unsafe.Pointer(&block[(v9 * 8)]))
		v9 = v9 + 1
	}
	v9 = 0
	for v9 < 8 {
		v8[v9] = h[v9]
		v9 = v9 + 1
	}
	v8[8] = uint64(0x6a09e667f3bcc908)
	v8[9] = uint64(0xbb67ae8584caa73b)
	v8[10] = uint64(0x3c6ef372fe94f82b)
	v8[11] = uint64(0xa54ff53a5f1d36f1)
	v8[12] = uint64(0x510e527fea90715d) ^ t0
	v8[13] = uint64(0x9b05688c2b3e6c1f) ^ t1
	v8[14] = uint64(0x1f83d9abfb41bd6b) ^ f0
	v8[15] = uint64(0x5be0cd19137e2179) ^ f1
	v10 = 0
	for v10 < 12 {
		v59 := v10 * 16
		v8[0] = (v8[0] + v8[4]) + v7[int(blake2b_sigma[v59])]
		v68 := v8[12] ^ v8[0]
		v8[12] = bits.RotateLeft64(v68, 32)
		v8[8] = v8[8] + v8[12]
		v92 := v8[4] ^ v8[8]
		v8[4] = bits.RotateLeft64(v92, 40)
		v8[0] = (v8[0] + v8[4]) + v7[int(blake2b_sigma[int(uint64(v59) + uint64(1))])]
		v127 := v8[12] ^ v8[0]
		v8[12] = bits.RotateLeft64(v127, 48)
		v8[8] = v8[8] + v8[12]
		v151 := v8[4] ^ v8[8]
		v8[4] = bits.RotateLeft64(v151, 1)
		v8[1] = (v8[1] + v8[5]) + v7[int(blake2b_sigma[(v59 + 2)])]
		v185 := v8[13] ^ v8[1]
		v8[13] = bits.RotateLeft64(v185, 32)
		v8[9] = v8[9] + v8[13]
		v209 := v8[5] ^ v8[9]
		v8[5] = bits.RotateLeft64(v209, 40)
		v8[1] = (v8[1] + v8[5]) + v7[int(blake2b_sigma[(v59 + 3)])]
		v244 := v8[13] ^ v8[1]
		v8[13] = bits.RotateLeft64(v244, 48)
		v8[9] = v8[9] + v8[13]
		v268 := v8[5] ^ v8[9]
		v8[5] = bits.RotateLeft64(v268, 1)
		v8[2] = (v8[2] + v8[6]) + v7[int(blake2b_sigma[(v59 + 4)])]
		v302 := v8[14] ^ v8[2]
		v8[14] = bits.RotateLeft64(v302, 32)
		v8[10] = v8[10] + v8[14]
		v326 := v8[6] ^ v8[10]
		v8[6] = bits.RotateLeft64(v326, 40)
		v8[2] = (v8[2] + v8[6]) + v7[int(blake2b_sigma[(v59 + 5)])]
		v361 := v8[14] ^ v8[2]
		v8[14] = bits.RotateLeft64(v361, 48)
		v8[10] = v8[10] + v8[14]
		v385 := v8[6] ^ v8[10]
		v8[6] = bits.RotateLeft64(v385, 1)
		v8[3] = (v8[3] + v8[7]) + v7[int(blake2b_sigma[(v59 + 6)])]
		v419 := v8[15] ^ v8[3]
		v8[15] = bits.RotateLeft64(v419, 32)
		v8[11] = v8[11] + v8[15]
		v443 := v8[7] ^ v8[11]
		v8[7] = bits.RotateLeft64(v443, 40)
		v8[3] = (v8[3] + v8[7]) + v7[int(blake2b_sigma[(v59 + 7)])]
		v478 := v8[15] ^ v8[3]
		v8[15] = bits.RotateLeft64(v478, 48)
		v8[11] = v8[11] + v8[15]
		v502 := v8[7] ^ v8[11]
		v8[7] = bits.RotateLeft64(v502, 1)
		v8[0] = (v8[0] + v8[5]) + v7[int(blake2b_sigma[(v59 + 8)])]
		v536 := v8[15] ^ v8[0]
		v8[15] = bits.RotateLeft64(v536, 32)
		v8[10] = v8[10] + v8[15]
		v560 := v8[5] ^ v8[10]
		v8[5] = bits.RotateLeft64(v560, 40)
		v8[0] = (v8[0] + v8[5]) + v7[int(blake2b_sigma[(v59 + 9)])]
		v595 := v8[15] ^ v8[0]
		v8[15] = bits.RotateLeft64(v595, 48)
		v8[10] = v8[10] + v8[15]
		v619 := v8[5] ^ v8[10]
		v8[5] = bits.RotateLeft64(v619, 1)
		v8[1] = (v8[1] + v8[6]) + v7[int(blake2b_sigma[(v59 + 10)])]
		v653 := v8[12] ^ v8[1]
		v8[12] = bits.RotateLeft64(v653, 32)
		v8[11] = v8[11] + v8[12]
		v677 := v8[6] ^ v8[11]
		v8[6] = bits.RotateLeft64(v677, 40)
		v8[1] = (v8[1] + v8[6]) + v7[int(blake2b_sigma[(v59 + 11)])]
		v712 := v8[12] ^ v8[1]
		v8[12] = bits.RotateLeft64(v712, 48)
		v8[11] = v8[11] + v8[12]
		v736 := v8[6] ^ v8[11]
		v8[6] = bits.RotateLeft64(v736, 1)
		v8[2] = (v8[2] + v8[7]) + v7[int(blake2b_sigma[(v59 + 12)])]
		v770 := v8[13] ^ v8[2]
		v8[13] = bits.RotateLeft64(v770, 32)
		v8[8] = v8[8] + v8[13]
		v794 := v8[7] ^ v8[8]
		v8[7] = bits.RotateLeft64(v794, 40)
		v8[2] = (v8[2] + v8[7]) + v7[int(blake2b_sigma[(v59 + 13)])]
		v829 := v8[13] ^ v8[2]
		v8[13] = bits.RotateLeft64(v829, 48)
		v8[8] = v8[8] + v8[13]
		v853 := v8[7] ^ v8[8]
		v8[7] = bits.RotateLeft64(v853, 1)
		v8[3] = (v8[3] + v8[4]) + v7[int(blake2b_sigma[(v59 + 14)])]
		v887 := v8[14] ^ v8[3]
		v8[14] = bits.RotateLeft64(v887, 32)
		v8[9] = v8[9] + v8[14]
		v911 := v8[4] ^ v8[9]
		v8[4] = bits.RotateLeft64(v911, 40)
		v8[3] = (v8[3] + v8[4]) + v7[int(blake2b_sigma[(v59 + 15)])]
		v946 := v8[14] ^ v8[3]
		v8[14] = bits.RotateLeft64(v946, 48)
		v8[9] = v8[9] + v8[14]
		v970 := v8[4] ^ v8[9]
		v8[4] = bits.RotateLeft64(v970, 1)
		v10 = v10 + 1
	}
	v9 = 0
	for v9 < 8 {
		h[v9] = (h[v9] ^ v8[v9]) ^ v8[(v9 + 8)]
		v9 = v9 + 1
	}
}

