// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package md5_transform

import (
	"encoding/binary"
	"math/bits"
)

type MD5_CTX_RAW struct {
	Count [2]uint32
	State [4]uint32
	Buffer [64]uint8
}

func Md5_transform_block(state []uint32, block []byte) {
	_ = block[63]
	a := state[0]
	b := state[1]
	c := state[2]
	d := state[3]
	var x [16]uint32
	for i := 0; i < 16; i++ {
		x[i] = binary.LittleEndian.Uint32(block[i*4:])
	}
	a = a + (((b&c)|(^b&d))+x[0]+uint32(0xd76aa478))
	a = bits.RotateLeft32(a, 7)
	a = a + b
	d = d + (((a&b)|(^a&c))+x[1]+uint32(0xe8c7b756))
	d = bits.RotateLeft32(d, 12)
	d = d + a
	c = c + (((d&a)|(^d&b))+x[2]+uint32(0x242070db))
	c = bits.RotateLeft32(c, 17)
	c = c + d
	b = b + (((c&d)|(^c&a))+x[3]+uint32(0xc1bdceee))
	b = bits.RotateLeft32(b, 22)
	b = b + c
	state[0] += a
	state[1] += b
	state[2] += c
	state[3] += d
}

