// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package siphash24

import (
	"encoding/binary"
	"math/bits"
)

func Siphash24(in []byte, inlen uint64, k []byte) uint64 {
	_ = k[15]
	k0 := binary.LittleEndian.Uint64(k[0:])
	k1 := binary.LittleEndian.Uint64(k[8:])
	v0 := uint64(0x736f6d6570736575) ^ k0
	v1 := uint64(0x646f72616d617461) ^ k1
	v2 := uint64(0x6c7967656e657261) ^ k0
	v3 := uint64(0x7465646279746573) ^ k1
	n := int(inlen)
	if n > len(in) { n = len(in) }
	end := n &^ 7
	for off := 0; off < end; off += 8 {
		mi := binary.LittleEndian.Uint64(in[off:])
		v3 ^= mi
		v0 += v1; v1 = bits.RotateLeft64(v1, 13); v1 ^= v0; v0 = bits.RotateLeft64(v0, 32)
		v2 += v3; v3 = bits.RotateLeft64(v3, 16); v3 ^= v2
		v0 += v3; v3 = bits.RotateLeft64(v3, 21); v3 ^= v0
		v2 += v1; v1 = bits.RotateLeft64(v1, 17); v1 ^= v2; v2 = bits.RotateLeft64(v2, 32)
		v0 += v1; v1 = bits.RotateLeft64(v1, 13); v1 ^= v0; v0 = bits.RotateLeft64(v0, 32)
		v2 += v3; v3 = bits.RotateLeft64(v3, 16); v3 ^= v2
		v0 += v3; v3 = bits.RotateLeft64(v3, 21); v3 ^= v0
		v2 += v1; v1 = bits.RotateLeft64(v1, 17); v1 ^= v2; v2 = bits.RotateLeft64(v2, 32)
		v0 ^= mi
	}
	var btail uint64
	for i := end; i < n; i++ {
		btail |= uint64(in[i]) << uint((i-end)*8)
	}
	btail |= uint64(n) << 56
	v3 ^= btail
	v0 += v1; v1 = bits.RotateLeft64(v1, 13); v1 ^= v0; v0 = bits.RotateLeft64(v0, 32)
	v2 += v3; v3 = bits.RotateLeft64(v3, 16); v3 ^= v2
	v0 += v3; v3 = bits.RotateLeft64(v3, 21); v3 ^= v0
	v2 += v1; v1 = bits.RotateLeft64(v1, 17); v1 ^= v2; v2 = bits.RotateLeft64(v2, 32)
	v0 += v1; v1 = bits.RotateLeft64(v1, 13); v1 ^= v0; v0 = bits.RotateLeft64(v0, 32)
	v2 += v3; v3 = bits.RotateLeft64(v3, 16); v3 ^= v2
	v0 += v3; v3 = bits.RotateLeft64(v3, 21); v3 ^= v0
	v2 += v1; v1 = bits.RotateLeft64(v1, 17); v1 ^= v2; v2 = bits.RotateLeft64(v2, 32)
	v0 ^= btail
	v2 ^= 0xff
	v0 += v1; v1 = bits.RotateLeft64(v1, 13); v1 ^= v0; v0 = bits.RotateLeft64(v0, 32)
	v2 += v3; v3 = bits.RotateLeft64(v3, 16); v3 ^= v2
	v0 += v3; v3 = bits.RotateLeft64(v3, 21); v3 ^= v0
	v2 += v1; v1 = bits.RotateLeft64(v1, 17); v1 ^= v2; v2 = bits.RotateLeft64(v2, 32)
	v0 += v1; v1 = bits.RotateLeft64(v1, 13); v1 ^= v0; v0 = bits.RotateLeft64(v0, 32)
	v2 += v3; v3 = bits.RotateLeft64(v3, 16); v3 ^= v2
	v0 += v3; v3 = bits.RotateLeft64(v3, 21); v3 ^= v0
	v2 += v1; v1 = bits.RotateLeft64(v1, 17); v1 ^= v2; v2 = bits.RotateLeft64(v2, 32)
	v0 += v1; v1 = bits.RotateLeft64(v1, 13); v1 ^= v0; v0 = bits.RotateLeft64(v0, 32)
	v2 += v3; v3 = bits.RotateLeft64(v3, 16); v3 ^= v2
	v0 += v3; v3 = bits.RotateLeft64(v3, 21); v3 ^= v0
	v2 += v1; v1 = bits.RotateLeft64(v1, 17); v1 ^= v2; v2 = bits.RotateLeft64(v2, 32)
	v0 += v1; v1 = bits.RotateLeft64(v1, 13); v1 ^= v0; v0 = bits.RotateLeft64(v0, 32)
	v2 += v3; v3 = bits.RotateLeft64(v3, 16); v3 ^= v2
	v0 += v3; v3 = bits.RotateLeft64(v3, 21); v3 ^= v0
	v2 += v1; v1 = bits.RotateLeft64(v1, 17); v1 ^= v2; v2 = bits.RotateLeft64(v2, 32)
	return v0 ^ v1 ^ v2 ^ v3
}

