// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package stbi_crc_dogfood

func Stbi_crc32_dogfood(buf []byte, len_ uint64) uint32 {
	var v2 uint32
	var v4 uint32
	var v5 int
	v2 = 0xffffffff
	v4 = 0
	for uint64(v4) < len_ {
		v2 = v2 ^ uint32(buf[int(v4)])
		v5 = 0
		for v5 < 8 {
			v2 = (v2 >> 1) ^ (0xedb88320 & -(v2 & 1))
			v5 = v5 + 1
		}
		v4 = v4 + 1
	}
	return ^v2
}

