// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package tweetnacl_dogfood

import (
	"encoding/binary"
	"math/bits"
)

var minusp = [17]uint64{5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 252}
var K = [80]uint64{0x428a2f98d728ae22, 0x7137449123ef65cd, 0xb5c0fbcfec4d3b2f, 0xe9b5dba58189dbbc, 0x3956c25bf348b538, 0x59f111f1b605d019, 0x923f82a4af194f9b, 0xab1c5ed5da6d8118, 0xd807aa98a3030242, 0x12835b0145706fbe, 0x243185be4ee4b28c, 0x550c7dc3d5ffb4e2, 0x72be5d74f27b896f, 0x80deb1fe3b1696b1, 0x9bdc06a725c71235, 0xc19bf174cf692694, 0xe49b69c19ef14ad2, 0xefbe4786384f25e3, 0x0fc19dc68b8cd5b5, 0x240ca1cc77ac9c65, 0x2de92c6f592b0275, 0x4a7484aa6ea6e483, 0x5cb0a9dcbd41fbd4, 0x76f988da831153b5, 0x983e5152ee66dfab, 0xa831c66d2db43210, 0xb00327c898fb213f, 0xbf597fc7beef0ee4, 0xc6e00bf33da88fc2, 0xd5a79147930aa725, 0x06ca6351e003826f, 0x142929670a0e6e70, 0x27b70a8546d22ffc, 0x2e1b21385c26c926, 0x4d2c6dfc5ac42aed, 0x53380d139d95b3df, 0x650a73548baf63de, 0x766a0abb3c77b2a8, 0x81c2c92e47edaee6, 0x92722c851482353b, 0xa2bfe8a14cf10364, 0xa81a664bbc423001, 0xc24b8b70d0f89791, 0xc76c51a30654be30, 0xd192e819d6ef5218, 0xd69906245565a910, 0xf40e35855771202a, 0x106aa07032bbd1b8, 0x19a4c116b8d2d0c8, 0x1e376c085141ab53, 0x2748774cdf8eeb99, 0x34b0bcb5e19b48a8, 0x391c0cb3c5c95a63, 0x4ed8aa4ae3418acb, 0x5b9cca4f7763e373, 0x682e6ff3d6b2b8a3, 0x748f82ee5defb2fc, 0x78a5636f43172f60, 0x84c87814a1f0ab72, 0x8cc702081a6439ec, 0x90befffa23631e28, 0xa4506cebde82bde9, 0xbef9a3f7b2c67915, 0xc67178f2e372532b, 0xca273eceea26619c, 0xd186b8c721c0c207, 0xeada7dd6cde0eb1e, 0xf57d4f7fee6ed178, 0x06f067aa72176fba, 0x0a637dc5a2c898a6, 0x113f9804bef90dae, 0x1b710b35131c471b, 0x28db77f523047d84, 0x32caab7b40c72493, 0x3c9ebe0a15c9bebc, 0x431d67c49c100d4c, 0x4cc5d4becb3e42b6, 0x597f299cfc657e2a, 0x5fcb6fab3ad6faec, 0x6c44198c4a475817}
var iv = [64]byte{0x6a, 0x09, 0xe6, 0x67, 0xf3, 0xbc, 0xc9, 0x08, 0xbb, 0x67, 0xae, 0x85, 0x84, 0xca, 0xa7, 0x3b, 0x3c, 0x6e, 0xf3, 0x72, 0xfe, 0x94, 0xf8, 0x2b, 0xa5, 0x4f, 0xf5, 0x3a, 0x5f, 0x1d, 0x36, 0xf1, 0x51, 0x0e, 0x52, 0x7f, 0xad, 0xe6, 0x82, 0xd1, 0x9b, 0x05, 0x68, 0x8c, 0x2b, 0x3e, 0x6c, 0x1f, 0x1f, 0x83, 0xd9, 0xab, 0xfb, 0x41, 0xbd, 0x6b, 0x5b, 0xe0, 0xcd, 0x19, 0x13, 0x7e, 0x21, 0x79}
var L = [32]uint64{0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9, 0xde, 0x14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x10}

func Randombytes(p []byte, n uint64) {
	var v2 uint64
	v2 = 0
	for v2 < n {
		p[int(v2)] = uint8((v2 * 17) + uint64(41))
		v2 = v2 + 1
	}
}

func Ld32(x []byte) uint64 {
	var v1 uint64
	v1 = uint64(x[3])
	v1 = (v1 << 8) | uint64(x[2])
	v1 = (v1 << 8) | uint64(x[1])
	return uint64((v1 << 8) | uint64(x[0]))
}

func Dl64(x []byte) uint64 {
	var v1 int
	var v2 uint64
	v2 = 0
	v1 = 0
	for v1 < 8 {
		v2 = (v2 << 8) | uint64(x[v1])
		v1 = v1 + 1
	}
	return v2
}

func Vn(x []byte, y []byte, n int) int {
	var v3 int
	var v4 uint64
	if n == 16 && len(x) >= 16 && len(y) >= 16 {
		d := binary.NativeEndian.Uint64(x[0:]) ^ binary.NativeEndian.Uint64(y[0:])
		d |= binary.NativeEndian.Uint64(x[8:]) ^ binary.NativeEndian.Uint64(y[8:])
		return int((1 & ((d - 1) >> 63)) - 1)
	}
	if n == 32 && len(x) >= 32 && len(y) >= 32 {
		var d uint64
		d |= binary.NativeEndian.Uint64(x[0:]) ^ binary.NativeEndian.Uint64(y[0:])
		d |= binary.NativeEndian.Uint64(x[8:]) ^ binary.NativeEndian.Uint64(y[8:])
		d |= binary.NativeEndian.Uint64(x[16:]) ^ binary.NativeEndian.Uint64(y[16:])
		d |= binary.NativeEndian.Uint64(x[24:]) ^ binary.NativeEndian.Uint64(y[24:])
		return int((1 & ((d - 1) >> 63)) - 1)
	}
	if n%8 == 0 && len(x) >= n && len(y) >= n {
		var d uint64
		for i := 0; i < n; i += 8 {
			d |= binary.NativeEndian.Uint64(x[i:]) ^ binary.NativeEndian.Uint64(y[i:])
		}
		return int((1 & ((d - 1) >> 63)) - 1)
	}
	v4 = 0
	v3 = 0
	{
		_x := x[:n]
		_y := y[:n]
		v3 = 0
		for v3 < n {
			v4 = v4 | uint64(_x[v3] ^ _y[v3])
			v3++
		}
	}
	return int((uint64(1) & ((v4 - 1) >> 8)) - uint64(1))
}

func Par25519(a []int64) uint8 {
	var _arr_v1 [32]uint8
	v1 := _arr_v1[:]
	Pack25519(v1, a)
	return uint8(v1[0] & uint8(1))
}

func Ch(x uint64, y uint64, z uint64) uint64 {
	return uint64((x & y) ^ (^x & z))
}

func Maj(x uint64, y uint64, z uint64) uint64 {
	return uint64(((x & y) ^ (x & z)) ^ (y & z))
}

func Sigma0(x uint64) uint64 {
	return uint64((bits.RotateLeft64(x, 64-(28)) ^ bits.RotateLeft64(x, 64-(34))) ^ bits.RotateLeft64(x, 64-(39)))
}

func Sigma1(x uint64) uint64 {
	return uint64((bits.RotateLeft64(x, 64-(14)) ^ bits.RotateLeft64(x, 64-(18))) ^ bits.RotateLeft64(x, 64-(41)))
}

func Sigma0_l(x uint64) uint64 {
	return uint64((bits.RotateLeft64(x, 64-(1)) ^ bits.RotateLeft64(x, 64-(8))) ^ (x >> 7))
}

func Sigma1_l(x uint64) uint64 {
	return uint64((bits.RotateLeft64(x, 64-(19)) ^ bits.RotateLeft64(x, 64-(61))) ^ (x >> 6))
}

func Pack25519(args ...any) {
	panic("sgoiter: Pack25519 was not harvested from the C source — this stub has no body")
}


