// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package utf8_iterate_dogfood

func Utf8_cl_dogfood(c uint8) uint64 {
	if c < 0x80 {
		return 1
	}
	if (c & 0xe0) == uint8(0xc0) {
		return 2
	}
	if (c & 0xf0) == uint8(0xe0) {
		return 3
	}
	if (c & 0xf8) == uint8(0xf0) {
		return 4
	}
	return 0
}

func Utf8_iterate2_dogfood(str []byte, len_ uint64) uint64 {
	if (str == nil) || (len_ == 0) {
		return 0xffffffff
	}
	v12 := Utf8_cl_dogfood(str[0])
	if (v12 == uint64(0)) || (v12 > len_) {
		return 0xffffffff
	}
	if v12 == uint64(1) {
		return uint64((uint64(1) << 32) | uint64(str[0]))
	}
	if v12 == uint64(2) {
		if (str[1] & uint8(0xc0)) != uint8(0x80) {
			return 0xffffffff
		}
		v46 := (uint64(uint32(str[0] & uint8(31))) << 6) | uint64(uint32(str[1] & uint8(63)))
		if v46 < uint64(0x80) {
			return 0xffffffff
		}
		return uint64((uint64(2) << 32) | v46)
	}
	return 0xffffffff
}

