// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package yyjson_digit_dogfood

func Yyjson_count_digits_dogfood(s []byte, len_ uint64) uint64 {
	var v2 uint64
	v2 = 0
	if s == nil {
		return 0
	}
	for v2 < len_ {
		v7 := s[int(v2)]
		if !(v7 >= '0') { break }
		if !(v7 <= '9') { break }
		v2 = v2 + 1
	}
	return v2
}

func Yyjson_skip_ws_dogfood(s []byte, len_ uint64) uint64 {
	var v2 uint64
	v2 = 0
	if s == nil {
		return 0
	}
	for v2 < len_ {
		if (((s[int(v2)] != uint8(32)) && (s[int(v2)] != uint8(9))) && (s[int(v2)] != uint8(10))) && (s[int(v2)] != uint8(13)) {
			return v2
		}
		v2 = v2 + 1
	}
	return v2
}

