// Code generated by sgoiter emit go127; DO NOT EDIT.
package c2vtparser

type C2_cell_t struct {
	Rune_ uint32
	Fg    uint8
	Bg    uint8
	Flags uint8
	Width uint8
}

type C2_vt_parser_t struct {
	State        int
	Cursor_x     int
	Cursor_y     int
	Cur_fg       int
	Cur_bg       int
	Cur_attr     int
	Width        int
	Height       int
	Prm          int
	Nparams      int
	Params       [4]int
	Pending_utf8 [4]uint8
	Pending_len  int
}

func C2_grid_clear(cells []C2_cell_t, n int, fg uint8, bg uint8) {
	var v4 int
	v4 = 0
	{
		_cells := cells[:n]
		v4 = 0
		for v4 < n {
			_cells[v4].Rune_ = 32
			_cells[v4].Fg = fg
			_cells[v4].Bg = bg
			_cells[v4].Flags = 0
			_cells[v4].Width = 1
			v4++
		}
	}
}

func C2_grid_clear_row(cells []C2_cell_t, y int, stride int, width int, fg uint8, bg uint8) {
	var v6 int
	v6 = 0
	for v6 < width {
		v13 := (y * stride) + v6
		cells[v13].Rune_ = 32
		cells[v13].Fg = fg
		cells[v13].Bg = bg
		cells[v13].Flags = 0
		cells[v13].Width = 1
		v6++
	}
}

func C2_grid_scroll_up(cells []C2_cell_t, width int, height int, stride int, nlines int) {
	var v5 int
	var v6 int
	var v7 int
	if nlines < 1 {
		return
	}
	if nlines > height {
		nlines = height
		_ = 0
	}
	v7 = height - nlines
	v5 = 0
	for v5 < v7 {
		v6 = 0
		for v6 < width {
			v25 := cells[int(((v5+nlines)*stride)+v6)]
			v27 := (v5 * stride) + v6
			cells[v27].Rune_ = v25.Rune_
			cells[v27].Fg = v25.Fg
			cells[v27].Bg = v25.Bg
			cells[v27].Flags = v25.Flags
			cells[v27].Width = v25.Width
			v6++
		}
		v5++
	}
	v5 = v7
	for v5 < height {
		C2_grid_clear_row(cells, v5, stride, width, uint8(0), uint8(0))
		v5++
	}
}

func C2_vt_init(p *C2_vt_parser_t, width int, height int) {
	p.State = 0
	p.Cursor_x = 0
	p.Cursor_y = 0
	p.Cur_fg = 0
	p.Cur_bg = 0
	p.Cur_attr = 0
	p.Width = width
	p.Height = height
	p.Prm = 0
	p.Nparams = 0
	p.Pending_len = 0
}

func C2_vt_put(p *C2_vt_parser_t, cells []C2_cell_t, r uint32) {
	var v7 int
	_ = 0
	v3 := p.Width
	v5 := p.Height
	if (v3 <= 0) || (v5 <= 0) {
		return
	}
	if p.Cursor_x >= v3 {
		p.Cursor_x = 0
		p.Cursor_y++
	}
	if p.Cursor_y >= v5 {
		p.Cursor_y = v5 - 1
	}
	v7 = (p.Cursor_y * v3) + p.Cursor_x
	cells[v7].Rune_ = r
	cells[v7].Fg = uint8(p.Cur_fg)
	cells[v7].Bg = uint8(p.Cur_bg)
	cells[v7].Flags = uint8(p.Cur_attr)
	cells[v7].Width = 1
	p.Cursor_x++
}

func C2_vt_add_digit(p *C2_vt_parser_t, b uint8) {
	var v2 int
	var v6 int
	v2 = int(b)
	v2 -= 48
	v6 = p.Prm
	v6 *= 10
	v6 += v2
	if v6 > 0x270f {
		v6 = 0x270f
	}
	p.Prm = v6
}

func C2_vt_finish_prm(p *C2_vt_parser_t) {
	_ = 0
	if p.Nparams < 4 {
		p.Params[p.Nparams] = p.Prm
		p.Nparams++
	}
	p.Prm = 0
}

func C2_vt_param(p *C2_vt_parser_t, i int, def int) int {
	_ = 0
	if (i < p.Nparams) && (p.Params[i] != 0) {
		return p.Params[i]
	}
	return def
}

func C2_vt_sgr(p *C2_vt_parser_t) {
	var v1 int
	_ = 0
	v1 = 0
	for v1 < p.Nparams {
		v10 := p.Params[v1]
		if v10 == 0 {
			p.Cur_fg = 0
			p.Cur_bg = 0
			p.Cur_attr = 0
		}
		if v10 == 1 {
			p.Cur_attr |= 1
		}
		if v10 == 4 {
			p.Cur_attr |= 4
		}
		if v10 == 7 {
			p.Cur_attr |= 8
		}
		if (v10 >= 30) && (v10 <= 37) {
			p.Cur_fg = v10 - 30
		}
		if (v10 >= 40) && (v10 <= 47) {
			p.Cur_bg = v10 - 40
		}
		v1++
	}
}

func C2_vt_clear_span(cells []C2_cell_t, i0 int, i1 int, fg uint8, bg uint8) {
	var v5 int
	v5 = i0
	for v5 < i1 {
		cells[v5].Rune_ = 32
		cells[v5].Fg = fg
		cells[v5].Bg = bg
		cells[v5].Flags = 0
		cells[v5].Width = 1
		v5++
	}
}

func C2_vt_csi(p *C2_vt_parser_t, cells []C2_cell_t, b uint8) {
	var v3 int
	var v4 int
	var v5 int
	var v6 int
	_ = 0
	C2_vt_finish_prm(p)
	v4 = p.Width
	v5 = p.Height
	if (b == 'H') || (b == 'f') {
		p.Cursor_y = C2_vt_param(p, 0, 1) - 1
		p.Cursor_x = C2_vt_param(p, 1, 1) - 1
		if p.Cursor_y < 0 {
			p.Cursor_y = 0
		}
		if p.Cursor_x < 0 {
			p.Cursor_x = 0
		}
		if (p.Height > 0) && (p.Cursor_y >= p.Height) {
			p.Cursor_y = p.Height - 1
		}
		if (p.Width > 0) && (p.Cursor_x >= p.Width) {
			p.Cursor_x = p.Width - 1
		}
	}
	if b == 'A' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_y -= v3
		if p.Cursor_y < 0 {
			p.Cursor_y = 0
		}
	}
	if b == 'B' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_y += v3
		if (p.Height > 0) && (p.Cursor_y >= p.Height) {
			p.Cursor_y = p.Height - 1
		}
	}
	if b == 'C' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_x += v3
		if (p.Width > 0) && (p.Cursor_x >= p.Width) {
			p.Cursor_x = p.Width - 1
		}
	}
	if b == 'D' {
		v3 = C2_vt_param(p, 0, 1)
		p.Cursor_x -= v3
		if p.Cursor_x < 0 {
			p.Cursor_x = 0
		}
	}
	if b == 'm' {
		C2_vt_sgr(p)
	}
	if b == 'J' {
		v3 = C2_vt_param(p, 0, 0)
		v6 = (p.Cursor_y * v4) + p.Cursor_x
		if v3 == 0 {
			C2_vt_clear_span(cells, v6, (v4 * v5), uint8(p.Cur_fg), uint8(p.Cur_bg))
		}
		if v3 == 1 {
			C2_vt_clear_span(cells, 0, (v6 + 1), uint8(p.Cur_fg), uint8(p.Cur_bg))
		}
		if v3 == 2 {
			C2_vt_clear_span(cells, 0, (v4 * v5), uint8(p.Cur_fg), uint8(p.Cur_bg))
		}
	}
	if b == 'K' {
		v3 = C2_vt_param(p, 0, 0)
		v6 = p.Cursor_y * v4
		if v3 == 0 {
			C2_vt_clear_span(cells, (v6 + p.Cursor_x), (v6 + v4), uint8(p.Cur_fg), uint8(p.Cur_bg))
		}
		if v3 == 1 {
			C2_vt_clear_span(cells, v6, ((v6 + p.Cursor_x) + 1), uint8(p.Cur_fg), uint8(p.Cur_bg))
		}
		if v3 == 2 {
			C2_vt_clear_span(cells, v6, (v6 + v4), uint8(p.Cur_fg), uint8(p.Cur_bg))
		}
	}
	p.State = 0
}

func C2_vt_feed_byte(p *C2_vt_parser_t, cells []C2_cell_t, b uint8) int {
	_ = 0
	if p.Height < 0 {
		cells[0].Rune_ = 0
	}
	switch p.State {
	case 0:
		if b == 27 {
			p.State = 1
			return 0
		}
		if b == 10 {
			p.Cursor_y++
			p.Cursor_x = 0
			return 1
		}
		if b == 13 {
			p.Cursor_x = 0
			return 1
		}
		if (b >= 32) && (b <= 0x7e) {
			C2_vt_put(p, cells, uint32(b))
			return 1
		}
	case 1:
		if b == 0x5b {
			p.State = 2
			p.Prm = 0
			p.Nparams = 0
			return 0
		}
		if b == 0x5d {
			p.State = 3
			return 0
		}
		p.State = 0
	case 2:
		if (b >= '0') && (b <= '9') {
			C2_vt_add_digit(p, b)
			return 0
		}
		if b == ';' {
			C2_vt_finish_prm(p)
			return 0
		}
		if (b >= 64) && (b <= 0x7e) {
			C2_vt_csi(p, cells, b)
			return 0
		}
	case 3:
		if (b == 7) || (b == 27) {
			p.State = 0
			return 0
		}
	}
	return 0
}
