// Code generated by sgoiter emit go127; DO NOT EDIT.
package tt55

type Tt55_font struct {
	Data                []byte
	Len_                uint64
	Cmap_off            uint32
	Cmap_len            uint32
	Cmap_sub            uint32
	Hmtx_off            uint32
	Hmtx_len            uint32
	Num_glyphs          uint16
	Number_of_h_metrics uint16
	Units_per_em        uint16
}

func Need(f *Tt55_font, off uint32, n uint32) int {
	_ = 0
	if f.Data == nil {
		return -1
	}
	if (uint64(off) + uint64(n)) > f.Len_ {
		return -2
	}
	return 0
}

func Be16(p []byte) uint16 {
	return uint16(uint16(uint16(p[0])<<8) | uint16(p[1]))
}

func Be32(p []byte) uint32 {
	return uint32(((uint32(uint32(p[0])<<24) | uint32(uint32(p[1])<<16)) | uint32(uint32(p[2])<<8)) | uint32(p[3]))
}

func Read16(f *Tt55_font, off uint32, out *uint16) int {
	v5 := Need(f, off, uint32(2))
	if v5 != 0 {
		return v5
	}
	*out = Be16(f.Data[off:][:])
	return 0
}

func Read32(f *Tt55_font, off uint32, out *uint32) int {
	v5 := Need(f, off, uint32(4))
	if v5 != 0 {
		return v5
	}
	*out = Be32(f.Data[off:][:])
	return 0
}

func Find_table(f *Tt55_font, ntab uint16, tag uint32, off *uint32, tlen *uint32) int {
	var v5 uint16
	var v14 uint32
	var v15 uint32
	var v16 int
	var v17 *uint32
	for v5 = 0; v5 < ntab; v5++ {
		v14 = 12 + (uint32(v5) * 16)
		v17 = &v15
		v16 = Read32(f, v14, v17)
		if v16 != 0 {
			return v16
		}
		if v15 == tag {
			v16 = Read32(f, (v14 + 8), off)
			if v16 != 0 {
				return v16
			}
			v16 = Read32(f, (v14 + 12), tlen)
			if v16 != 0 {
				return v16
			}
			return 0
		}
	}
	return -2
}

func Pick_cmap(f *Tt55_font, sub_off *uint32) int {
	var v2 uint16
	var v3 uint16
	var v4 uint32
	var v6 int
	var v8 int
	var v12 *uint16
	var v17 uint16
	var v25 uint32
	var v26 uint16
	var v27 uint16
	var v28 uint32
	var v30 uint16
	var v31 *uint16
	var v36 *uint16
	var v41 *uint32
	var v45 uint32
	var v46 *uint16
	v4 = 0
	v6 = 0
	v12 = &v2
	v8 = Read16(f, (f.Cmap_off + 2), v12)
	if v8 != 0 {
		return v8
	}
	v3 = 0
	for v3 < v2 {
		v25 = (f.Cmap_off + 4) + (uint32(v3) * 8)
		v31 = &v26
		v8 = Read16(f, v25, v31)
		if v8 != 0 {
			return v8
		}
		v36 = &v27
		v8 = Read16(f, (v25 + 2), v36)
		if v8 != 0 {
			return v8
		}
		v41 = &v28
		v8 = Read32(f, (v25 + 4), v41)
		if v8 != 0 {
			return v8
		}
		v45 = f.Cmap_off + v28
		v46 = &v30
		v8 = Read16(f, v45, v46)
		if v8 != 0 {
			return v8
		}
		if (v30 != 4) && (v30 != 12) {
			v17 = v3 + 1
			v3 = v17
			continue
		}
		if ((v26 == 3) && (v27 == 10)) && (v30 == 12) {
			*sub_off = v45
			return 0
		}
		if ((v26 == 3) && (v27 == 1)) && (v30 == 4) {
			v4 = v45
			v6 = 1
		} else {
			if (v26 == 0) && (v6 == 0) {
				v4 = v45
				v6 = 1
			}
		}
		v17 = v3 + 1
		v3 = v17
	}
	if v6 == 0 {
		return -3
	}
	*sub_off = v4
	return 0
}

func Tt55_open(data []byte, len_ uint64, font *Tt55_font) int {
	var v3 uint32
	var v4 uint16
	var v5 uint32
	var v6 uint32
	var v7 uint32
	var v8 uint32
	var v9 uint32
	var v10 uint32
	var v11 uint32
	var v12 uint32
	var v13 int
	var v26 *uint32
	var v41 *uint16
	var v54 *uint32
	var v56 *uint32
	var v63 *uint32
	var v64 *uint32
	var v75 *uint32
	var v76 *uint32
	var v88 *uint32
	var v90 *uint32
	var v97 *uint32
	var v98 *uint32
	var v110 *uint32
	var v123 *uint16
	var v129 *uint16
	var v135 *uint16
	var v145 *uint32
	_ = 0
	if ((data == nil) || (font == nil)) || (len_ < 12) {
		return -1
	}
	font.Data = data[:]
	font.Len_ = len_
	v26 = &v3
	v13 = Read32(font, uint32(0), v26)
	if v13 != 0 {
		return v13
	}
	if ((v3 != 0x10000) && (v3 != 0x74727565)) && (v3 != 0x4f54544f) {
		return -2
	}
	v41 = &v4
	v13 = Read16(font, uint32(4), v41)
	if v13 != 0 {
		return v13
	}
	if (v4 == 0) || (v4 > 64) {
		return -2
	}
	v54 = &font.Cmap_off
	v56 = &font.Cmap_len
	v13 = Find_table(font, v4, uint32(0x636d6170), v54, v56)
	if v13 != 0 {
		return -3
	}
	v63 = &v5
	v64 = &v6
	v13 = Find_table(font, v4, uint32(0x68656164), v63, v64)
	if (v13 != 0) || (v6 < 54) {
		return -2
	}
	v75 = &v7
	v76 = &v8
	v13 = Find_table(font, v4, uint32(0x68686561), v75, v76)
	if (v13 != 0) || (v8 < 36) {
		return -4
	}
	v88 = &font.Hmtx_off
	v90 = &font.Hmtx_len
	v13 = Find_table(font, v4, uint32(0x686d7478), v88, v90)
	if v13 != 0 {
		return -4
	}
	v97 = &v9
	v98 = &v10
	v13 = Find_table(font, v4, uint32(0x6d617870), v97, v98)
	if (v13 != 0) || (v10 < 6) {
		return -2
	}
	v110 = &v11
	v13 = Read32(font, (v5 + 12), v110)
	if (v13 != 0) || (v11 != 0x5f0f3cf5) {
		return -2
	}
	v123 = &font.Units_per_em
	v13 = Read16(font, (v5 + 18), v123)
	if v13 != 0 {
		return v13
	}
	v129 = &font.Num_glyphs
	v13 = Read16(font, (v9 + 4), v129)
	if v13 != 0 {
		return v13
	}
	v135 = &font.Number_of_h_metrics
	v13 = Read16(font, (v7 + 34), v135)
	if v13 != 0 {
		return v13
	}
	if font.Number_of_h_metrics == 0 {
		return -4
	}
	v145 = &v12
	v13 = Pick_cmap(font, v145)
	if v13 != 0 {
		return v13
	}
	font.Cmap_sub = v12
	return 0
}

func Glyph_fmt4(f *Tt55_font, cp uint32, gid *uint16) int {
	var v3 uint16
	var v5 uint16
	var v6 uint32
	var v8 int
	var v14 *uint16
	var v27 uint16
	var v28 uint16
	var v29 uint16
	var v30 uint16
	var v37 *uint16
	var v50 *uint16
	var v66 *uint16
	var v79 *uint16
	var v107 uint16
	var v108 *uint16
	v6 = f.Cmap_sub
	if cp > 0xffff {
		*gid = 0
		return 0
	}
	v14 = &v3
	v8 = Read16(f, (v6 + 6), v14)
	if v8 != 0 {
		return v8
	}
	v18 := v3 / 2
	if v18 == 0 {
		return -2
	}
	v5 = 0
	for v5 < v18 {
		v37 = &v27
		v8 = Read16(f, ((v6 + 14) + (uint32(v5) * 2)), v37)
		if v8 != 0 {
			return v8
		}
		v50 = &v28
		v8 = Read16(f, (((v6 + 16) + (uint32(v18) * 2)) + (uint32(v5) * 2)), v50)
		if v8 != 0 {
			return v8
		}
		if (cp < uint32(v28)) || (cp > uint32(v27)) {
			v5++
			continue
		}
		v66 = &v29
		v8 = Read16(f, (((v6 + 16) + (uint32(v18) * 4)) + (uint32(v5) * 2)), v66)
		if v8 != 0 {
			return v8
		}
		v79 = &v30
		v8 = Read16(f, (((v6 + 16) + (uint32(v18) * 6)) + (uint32(v5) * 2)), v79)
		if v8 != 0 {
			return v8
		}
		if v30 == 0 {
			*gid = uint16(cp) + v29
			return 0
		}
		v108 = &v107
		v8 = Read16(f, (((((v6 + 16) + (uint32(v18) * 6)) + (uint32(v5) * 2)) + uint32(v30)) + (uint32(2) * (cp - uint32(v28)))), v108)
		if v8 != 0 {
			return v8
		}
		if v107 != 0 {
			v107 += v29
		}
		*gid = v107
		return 0
	}
	*gid = 0
	return 0
}

func Glyph_fmt12(f *Tt55_font, cp uint32, gid *uint16) int {
	var v3 uint32
	var v4 uint32
	var v5 uint32
	var v7 int
	var v10 *uint32
	var v21 uint32
	var v22 uint32
	var v23 uint32
	var v24 uint32
	var v25 *uint32
	var v30 *uint32
	var v38 *uint32
	var v43 uint32
	v5 = f.Cmap_sub
	v10 = &v3
	v7 = Read32(f, (v5 + 12), v10)
	if v7 != 0 {
		return v7
	}
	v4 = 0
	for v4 < v3 {
		v21 = (v5 + 16) + (v4 * 12)
		v25 = &v22
		v7 = Read32(f, v21, v25)
		if v7 != 0 {
			return v7
		}
		v30 = &v23
		v7 = Read32(f, (v21 + 4), v30)
		if v7 != 0 {
			return v7
		}
		if (cp < v22) || (cp > v23) {
			v4++
			continue
		}
		v38 = &v24
		v7 = Read32(f, (v21 + 8), v38)
		if v7 != 0 {
			return v7
		}
		v43 = v24 + (cp - v22)
		if v43 > 0xffff {
			return -2
		}
		*gid = uint16(v43)
		return 0
	}
	*gid = 0
	return 0
}

func Tt55_glyph(font *Tt55_font, cp uint32, gid *uint16) int {
	var v3 uint16
	var v18 *uint16
	if ((font == nil) || (gid == nil)) || (font.Data == nil) {
		return -1
	}
	v18 = &v3
	v19 := Read16(font, font.Cmap_sub, v18)
	if v19 != 0 {
		return v19
	}
	if v3 == 4 {
		return Glyph_fmt4(font, cp, gid)
	}
	if v3 == 12 {
		return Glyph_fmt12(font, cp, gid)
	}
	return -3
}

func Tt55_advance(font *Tt55_font, gid uint16, aw *uint16) int {
	var v3 uint32
	_ = 0
	if ((font == nil) || (aw == nil)) || (font.Data == nil) {
		return -1
	}
	if gid >= font.Num_glyphs {
		return -2
	}
	v3 = uint32(gid)
	if v3 >= uint32(font.Number_of_h_metrics) {
		v3 = uint32(font.Number_of_h_metrics) - 1
	}
	v35 := Read16(font, (font.Hmtx_off + (v3 * 4)), aw)
	if v35 != 0 {
		return v35
	}
	return 0
}
