// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package fast_xor

import "unsafe"

func Fast_xor_bytes(dst []byte, src1 []byte, src2 []byte, len_ uint64) {
	n := int(len_)
	i := 0
	dp := unsafe.SliceData(dst)
	ap := unsafe.SliceData(src1)
	bp := unsafe.SliceData(src2)
	for ; i+16 <= n; i += 16 {
		*(*uint64)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*uint64)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*uint64)(unsafe.Add(unsafe.Pointer(bp), i))
		*(*uint64)(unsafe.Add(unsafe.Pointer(dp), i+8)) = *(*uint64)(unsafe.Add(unsafe.Pointer(ap), i+8)) ^ *(*uint64)(unsafe.Add(unsafe.Pointer(bp), i+8))
	}
	for ; i+8 <= n; i += 8 {
		*(*uint64)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*uint64)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*uint64)(unsafe.Add(unsafe.Pointer(bp), i))
	}
	switch n - i {
	case 7:
		*(*byte)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*byte)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*byte)(unsafe.Add(unsafe.Pointer(bp), i))
		i++
		fallthrough
	case 6:
		*(*byte)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*byte)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*byte)(unsafe.Add(unsafe.Pointer(bp), i))
		i++
		fallthrough
	case 5:
		*(*byte)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*byte)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*byte)(unsafe.Add(unsafe.Pointer(bp), i))
		i++
		fallthrough
	case 4:
		*(*byte)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*byte)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*byte)(unsafe.Add(unsafe.Pointer(bp), i))
		i++
		fallthrough
	case 3:
		*(*byte)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*byte)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*byte)(unsafe.Add(unsafe.Pointer(bp), i))
		i++
		fallthrough
	case 2:
		*(*byte)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*byte)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*byte)(unsafe.Add(unsafe.Pointer(bp), i))
		i++
		fallthrough
	case 1:
		*(*byte)(unsafe.Add(unsafe.Pointer(dp), i)) = *(*byte)(unsafe.Add(unsafe.Pointer(ap), i)) ^ *(*byte)(unsafe.Add(unsafe.Pointer(bp), i))
	}
}

