// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package fnv1a_64

func Fnv1a_64(data []byte, len_ uint64) uint64 {
	var v2 uint64
	v2 = 0xcbf29ce484222325
	n := int(len_)
	i := 0
	for ; i+8 <= n; i += 8 {
		b := data[i : i+8]
		v2 = (v2 ^ uint64(b[0])) * 0x100000001b3
		v2 = (v2 ^ uint64(b[1])) * 0x100000001b3
		v2 = (v2 ^ uint64(b[2])) * 0x100000001b3
		v2 = (v2 ^ uint64(b[3])) * 0x100000001b3
		v2 = (v2 ^ uint64(b[4])) * 0x100000001b3
		v2 = (v2 ^ uint64(b[5])) * 0x100000001b3
		v2 = (v2 ^ uint64(b[6])) * 0x100000001b3
		v2 = (v2 ^ uint64(b[7])) * 0x100000001b3
	}
	for ; i < n; i++ {
		v2 = (v2 ^ uint64(data[i])) * 0x100000001b3
	}
	return v2
}

