// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package murmur3_x86_32

import (
	"math/bits"
	"unsafe"
)

func Fmix32(h uint32) uint32 {
	h = h ^ (h >> 16)
	h = h * 0x85ebca6b
	h = h ^ (h >> 13)
	h = h * 0xc2b2ae35
	h = h ^ (h >> 16)
	return h
}

func Murmur3_x86_32(key []byte, len_ uint64, seed uint32) uint32 {
	var v8 uint32
	var v23 uint32
	var v44 uint32
	v7 := int(len_ / uint64(4))
	v8 = seed
	v9 := uint32(0xcc9e2d51)
	v11 := uint32(0x1b873593)
	j := 0
	for j < v7 {
		v23 = *(*uint32)(unsafe.Pointer(&key[int((j * 4))]))
		v23 = v23 * v9
		v23 = bits.RotateLeft32(v23, 15)
		v23 = v23 * v11
		v8 = v8 ^ v23
		v8 = bits.RotateLeft32(v8, 13)
		v8 = (v8 * 5) + 0xe6546b64
		j = j + 1
	}
	v41 := v7 * 4
	v44 = 0
	switch uint32(len_ & 3) {
		case 3:
			v44 = v44 ^ (uint32(key[(v41 + 2)]) << 16)
		fallthrough
		case 2:
			v44 = v44 ^ (uint32(key[(v41 + 1)]) << 8)
		fallthrough
		case 1:
			v44 = v44 ^ uint32(key[v41])
			v44 = v44 * v9
			v44 = bits.RotateLeft32(v44, 15)
			v44 = v44 * v11
			v8 = v8 ^ v44
	}
	v8 = v8 ^ uint32(len_)
	return Fmix32(v8)
}

