// Code generated by sgoiter emit go1.26; DO NOT EDIT.
// emit mode=kernel (unsafe LE word paths where documented)
package strlenspn_lab

var accept_hel = [4]byte{104, 101, 108, 0}

func Strlenspn_lab(s []byte, n uint64) uint64 {
	nn := int(n)
	if nn > len(s) { nn = len(s) }
	s = s[:nn]
	i := 0
	for i < nn {
		c := s[i]
		ok := c == 'h' || c == 'e' || c == 'l'
		if !ok { break }
		i++
	}
	return uint64(i)
}

